# Ch1 — see opus55-findings.md "Ch1"
from apply import E

HUN_RAW_OLD = ("*„Közöttünk van Allah Küldötte (ﷺ), az Ő (ﷻ) Könyvét recitálva,*\n\n"
               "*amikor a napfény rejtett sugara hasítja a hajnalt. Vakság után megmutatta nekünk az útmutatást,*\n\n"
               "*így szívünk hisz benne, hogy amit mond, igaz. Éjjel elhagyja fekhelyét,*\n\n"
               "*amikor az ágyak álomtól nehezítik el a bálványimádókat.\"*")
HUN_RAW_NEW = ("*„Közöttünk van Allah Küldötte (ﷺ), az Ő (ﷻ) Könyvét recitálja, amikor feltör a hajnal rejtett ragyogása.*\n\n"
               "*Vakság után megmutatta nekünk az útmutatást, így szívünk bizonyos benne, hogy amit mond, beteljesedik.*\n\n"
               "*Éjjel oldalát távol tartja fekhelyétől, amikor a bálványimádókat elnehezíti ágyuk.\"*")
ENG_RAW_OLD = ("\"Among us is the Messenger of Allāh (ﷺ) reciting His (ﷻ) Book.\n\n"
               "When a hidden ray of sunlight splits the dawn. He showed us guidance after blindness.\n\n"
               "So our hearts have faith in him, that what he says is true. At night he forsakes his bed.\n\n"
               "When beds make the idolaters heavy with sleep.\"")
ENG_RAW_NEW = ("*\"Among us is the Messenger of Allāh (ﷺ) reciting His (ﷻ) Book, when the hidden brightness of dawn breaks forth.*\n\n"
               "*He showed us guidance after blindness, so our hearts are certain that what he says will come to pass.*\n\n"
               "*At night he keeps his side away from his bed, when their beds weigh heavy upon the idolaters.\"*")

EDITS = [
    E("HUN", "1.150", "az Ísza (Jézus), Maryam (Mária) fiának vallásán", "'Īsā (Jézus) (عليه السلام), Maryam (Mária) fiának vallásán"),
    E("HUN", "1.152", "A perzsa mágia makacsul", "A perzsiai mágusvallás makacsul"),
    E("HUN", "1.154", "Mondjátok: „Bizony, akik hazugságot eszelnek ki", "Mondd: „Bizony, akik hazugságot eszelnek ki"),
    E("HUN", "1.168", "\nEljöttél, miközben az emberek zűrzavarban éltek; ha elmentél volna mellettük, láttad volna, hogy bálványt bálvány után imádnak.\n",
      "\n*Eljöttél, miközben az emberek zűrzavarban éltek; ha elmentél volna mellettük, láttad volna, hogy bálványt bálvány után imádnak.*\n"),
    E("HUN", "1.170", "\nRóma királya elnyomta népét, Perzsia királya pedig büszkeségétől siket és vak volt.\n",
      "\n*Róma királya elnyomta népét, Perzsia királya pedig büszkeségétől siket és vak volt.*\n"),
    E("ENG", "1.168", "\nYou came, while the people were in chaos: if you had passed by them you would have seen them worshipping idol upon idol. The king of Rome oppressed his people and the king of Persia was deaf and blind from pride.\n",
      "\n*You came, while the people were in chaos: if you had passed by them you would have seen them worshipping idol upon idol.*\n\n*The king of Rome oppressed his people and the king of Persia was deaf and blind from pride.*\n"),
    E("HUN", "1.180", "olyanok voltak, mint bezárt gyermekek.", "olyanok voltak, mint a gyámság alatt álló gyermek."),
    E("ENG", "1.180", "were like confined children.", "were like a child under guardianship."),
    E("HUN", "1.186", "Ha tehát azt látod, hogy gyermekek figyelmen kívül hagyják tanáruk leckéit, vagy ruhájába kapaszkodnak, amíg él, illetve holmijához ragaszkodnak halála után – tudd, hogy méltatlan tanítványok. Nem méltók arra, hogy az Üzenet tanítása szóljon hozzájuk, nemhogy szilárdan álljanak az útján.",
      "Ha tehát azt látod, hogy némelyek elfeledkeznek a tanító leckéiről, és ruhájába kapaszkodnak, amíg él, vagy földi maradványaihoz ragaszkodnak halála után – tudd, hogy az ilyen ember naiv gyermek. Nem méltó arra, hogy az Üzenet tanításai szóljanak hozzá, nemhogy szilárdan járjon az útján."),
    E("ENG", "1.186", "So if you see children ignoring their teacher's lessons or clinging to his clothes while he is alive or holding onto his belongings after he is dead, then know that he is unworthy children. He is not fit to be addressed by the teaching of the Message, let alone standing firmly on its path.",
      "So if you see some people neglecting the teacher's lessons, clinging to his clothes while he is alive or holding onto his remains after he is dead, then know that such a person is a naive child. He is not fit to be addressed by the teachings of the Message, let alone to stand firmly on its path."),
    E("HUN", "1.188", "irtózattal fordulna el tőlük, és utálna a közelükben lenni.", "helytelenítené, hogy ott tanyáznak mellette."),
    E("ENG", "1.188", "he would abhor the sight of them and hate to be near them.", "he would disapprove of their staying near him."),
    E("HUN", "1.192a", "jobban ismerik a Próféta (ﷺ) titkát, mint ti.", "jobban ismerik Mohamed (ﷺ) valódi mivoltát, mint ti."),
    E("ENG", "1.192a", "know the secret of the Prophet (ﷺ) better than you.", "know the reality of Muhammad (ﷺ) better than you."),
    E("HUN", "1.192b", "„Szeresd Allahot (ﷻ) azért a bőkezűségért, amellyel ellát benneteket, és engem szeressetek", "„Szeressétek Allahot (ﷻ) az adományokért, amelyekkel táplál benneteket, és engem szeressetek"),
    E("HUN", "1.192c", "az adományokért, amelyekkel elhalmoz benneteket, és engem szeressetek", "az adományokért, amelyekkel táplál benneteket, és engem szeressetek"),
    E("HUN", "1.196", "Az iszlám prófétája (ﷺ) soha nem nevezte ki magát a megbocsátás és az áldás „kapujának\". Egyetlen napig sem tette ezt, mert soha nem folytatta a szélhámosok mesterségét.",
      "Az iszlám Prófétája (ﷺ) ráadásul soha nem tette meg magát „pápának\", aki bűnbocsánatot osztogat az embereknek és áldásokat adományoz. Egyetlen napig sem tette ezt, mert soha nem űzött szemfényvesztést!"),
    E("ENG", "1.196", "did not appoint himself as a \"gateway\" for forgiveness and blessings. He never did so for a single day, because he was never implicated in swindling.",
      "did not appoint himself a \"Pope\" who grants forgiveness to people and bestows blessings. He never did so for a single day, because he never engaged in charlatanry!"),
    E("HUN", "1.198", "([Egyedül] Téged imádunk és [egyedül] Tőled kérünk segítséget. Vezess minket az egyenes útra; azok útjára, akiket keggyel halmoztal el; ne azok útjára, akik haragodat vonták magukra, és ne az eltévelyedettekére.) (Korán 1: 5–7)",
      "(Vezess minket az egyenes útra; azok útjára, akiket keggyel halmoztál el; ne azok útjára, akik haragodat vonták magukra, és ne az eltévelyedettekére.) (Korán 1: 6–7)"),
    E("ENG", "1.198", "(You [Alone] we worship, and you [Alone] we ask for help [for each and everything]. Show us the straight path;", "(Show us the straight path;"),
    E("ENG", "1.198b", "nor of those who go astray.) (Qur'ān 1: 5-7)", "nor of those who go astray.) (Qur'ān 1: 6-7)"),
    E("HUN", "1.204", "Nem Mohamed feladata, hogy", "Nem Mohamed (ﷺ) feladata, hogy"),
    E("ENG", "1.204", "It is not Muhammad's task to drag you", "It is not Muhammad's (ﷺ) task to drag you"),
    E("HUN", "1.238a", "E tó (Medina) népe már összegyűlt", "E település (Medina) népe már összegyűlt"),
    E("ENG", "1.238a", "The people of this lake (Madīnah) had assembled", "The people of this town (Madīnah) had assembled"),
    E("HUN", "1.238b", "ez meghiúsította őt. Ez vitte rá", "ez a torkán akadt. Ez vitte rá"),
    E("ENG", "1.238b", "he was outmatched by that. And that is", "he choked on it. And that is"),
    E("HUN", "1.242", "A tudatlanság ez egyszerű vagy összetett formái, e szándékos vagy megtévedt ellenségeskedések közepette,", "A tudatlanság eme egyszerű vagy összetett formái és eme szándékos vagy megtévedt ellenségeskedések közepette,"),
    E("HUN", "1.256", "ezeket a törekvő költőket és forradalmárokat", "ezeket a törekvő költőket és prózaírókat"),
    E("ENG", "1.256", "these aspiring poets and revolutionaries", "these aspiring poets and prose-writers"),
    E("HUN", "1.274", "És Ő minden teremtés Mindentudója. Ő, Aki tüzet ad", "És Ő minden teremtés Mindentudója.\" Ő, Aki tüzet ad"),
    E("HUN", "1.286", "és nem tartozott Al Mushrikūn [a többistenhívők] közé. Mondd", "és nem tartozott Al Mushrikūn [a többistenhívők] közé.\" Mondd"),
    E("ENG", "1.286a", "and he was not of Al Mushrikūn [Polytheists]. Say", "and he was not of Al Mushrikūn [Polytheists].\" Say"),
    E("ENG", "1.286b", "[mankind, jinn and all that exists]. \"He has no partner.", "[mankind, jinn and all that exists]. He has no partner."),
    E("HUN", "1.290", "Ha az emberek megvallják bűneiket, nem ők néznek szembe a büntetéssel: az áldozatot egy letűnt korban mutatták be ezekért a bűnökért, és ebben hinniük kell, ha üdvözülni akarnak!",
      "Ha az ember bűnt követ el, nem ő viseli a büntetést: az áldozatot réges-régen bemutatták ezért a vétkéért, és ezt kell elhinnie, ha üdvözülni akar!"),
    E("ENG", "1.290", "If people confess to sins, it is not they who face the penalty: the sacrifice was offered in a past age for these sins, and they must believe in that if they want to gain salvation!",
      "If a person commits a sin, it is not he who faces the penalty: the sacrifice was offered long ago for that sin of his, and he must believe in that if he wants to gain salvation!"),
    E("HUN", "1.306", "És ne szólíts Allah mellett más istent.\") (Korán 28: 87–88)", "És ne szólíts Allah mellett más istent. Nincs más isten, csak Ő.\") (Korán 28: 87–88)"),
    E("ENG", "1.306", "And do not call any other god along with Allāh\") (Qur'ān 28: 87-88)", "And do not call any other god along with Allāh; there is no god but He.\") (Qur'ān 28: 87-88)"),
    E("HUN", "1.312", "(Ne meressze szemed arra, amit egyes házaspároknak közülük élvezetül adtunk,", "(Ne vesd vágyakozó tekinteted arra, amit egyes csoportjaiknak élvezetül adtunk,"),
    E("HUN", "1.326", "A megszólításnak ez a módja ott zeng a fülekben, és célja van.", "A megszólításnak ez a módja ott zeng a fülünkben, és célja van, ahogy a mondás tartja: „Lányomnak mondom, menyem értsen belőle.\""),
    E("ENG", "1.326", "This mode of address resounds in the ears and it is used for a purpose.", "This mode of address resounds in our ears and it has a purpose, as the saying goes: \"It is you I mean, but listen, O neighbour!\""),
    E("HUN", "1.348", "Az iszlám a nevelés szempontjából az igazság ismerete;", "Az iszlám értelmi szempontból az igazság ismerete;"),
    E("ENG", "1.348", "Islām from the educational point of view is knowledge of the truth,", "Islām from the intellectual point of view is knowledge of the truth,"),
    E("HUN", "1.370a", "A Próféták (ﷺ) nyomdokainak követése maga a teljes erény, és mint ilyen, Mohamed (ﷺ) Szunnája a Korán melletti elsődleges törvényforrássá tétetett, amellyel Allah (ﷻ) megtisztelte őt és az összes muszlimot.",
      "A küldöttek nyomdokainak követése maga a teljes jó, és ezért lett Mohamed (ﷺ) Szunnája törvényének forrása a Könyv mellett, amellyel Allah (ﷻ) megtisztelte őt. A muszlimok többsége így érti ezt."),
    E("ENG", "1.370a", "To follow the footsteps of the Prophets (ﷺ) is total virtue and, as such, the Sunnah of Muhammad (ﷺ) was made a primary source of law along with the Qur'ān by which Allāh (ﷻ) honoured him and all the Muslims.",
      "To follow in the footsteps of the Messengers is the whole of goodness, and for this reason the Sunnah of Muhammad (ﷺ) became a source of his Law along with the Book with which Allāh (ﷻ) honoured him. The majority of Muslims hold this understanding."),
    E("HUN", "1.370b", "A tőle közölt dolgokat el kell fogadni, ám gondosan meg kell vizsgálni őket, mielőtt hitelesként elfogadtatnak — a múltban történt torzítások miatt. Nem minden, ami hitelesen bizonyítottan tőle származik, értetik mindig helyesen, vagy kapja meg az őt megillető helyet.",
      "A hagyományozott szunnák átvétele azonban éberséget kíván: nem minden, amit a Küldöttnek (ﷺ) tulajdonítanak, elfogadható szunna, és nem mindaz, aminek eredete hiteles, értetik helyesen, vagy kerül a maga helyére!"),
    E("ENG", "1.370b", "The things that are reported from him must be adopted, however, be scrutinized carefully before they are accepted as genuine, because of the distortions which occurred in the past. Not everything which is authentically proved to come from him is always understood correctly or given its rightful position.",
      "However, the transmitted Sunnah calls for vigilance in receiving it: not everything ascribed to the Messenger (ﷺ) is an acceptable Sunnah, and not everything whose ascription is authentic is correctly understood or put in its proper place!"),
    E("HUN", "1.376", "A Korán az iszlám egyedüli alkotmánya;", "A Korán az iszlám alapvető alkotmánya;"),
    E("ENG", "1.376", "The Qur'ān is the sole constitution of Islām,", "The Qur'ān is the fundamental constitution of Islām,"),
    E("HUN", "1.382", "Egy nap eljött, biztosan Allah döntésében, és így szólt:", "Egy reggel aztán, miután Allah (ﷻ) döntésre juttatta, így szólt:"),
    E("ENG", "1.382", "One day he came, confident of Allāh's decision, and said:", "Then one morning, Allāh having settled his resolve, he said:"),
    E("HUN", "1.402", "a Prófétától (ﷺ) — béke legyen vele — való idézéseiteket", "a Prófétától (ﷺ) való idézéseiteket"),
    E("ENG", "1.402", "your quotations from the Prophet (ﷺ), peace be upon him.", "your quotations from the Prophet (ﷺ)."),
    E("HUN", "1.410", "(1) Nem lepődtök meg Abū Hurairán (رضي الله عنه)?", "Nem csodálkozol Abū Hurairán (رضي الله عنه)?"),
    E("ENG", "1.410", "(1) Are you not surprised at Abū Hurairah", "Are you not surprised at Abū Hurairah"),
    E("HUN", "1.414", "Valójában a muszlimokat ilyen módon elfoglalni a vallás elleni vétek.", "Sőt, még a muszlimoknak a Koránnal való ilyetén lefoglalása sem tartozik a valláshoz."),
    E("ENG", "1.414", "In fact, to occupy the Muslims with the Qur'ān in this manner is to trespass on the religion.", "Indeed, even occupying the Muslims with the Qur'ān in this manner is not part of the religion."),
    E("HUN", "1.432", "Nem tilos megérteni nélkül memorizálni; az tilos, hogy az ember helytelenül értsen.", "A veszély azonban nem a megértés nélküli memorizálásban rejlik, hanem abban, hogy az ember helytelenül értse a dolgot."),
    E("ENG", "1.432", "It is not forbidden to memorize without understanding. What is forbidden is that, one should understand incorrectly.", "What is to be feared, however, is not memorizing without understanding, but understanding the matter wrongly."),
    E("HUN", "1.440", "az események félreértése folytán.", "egy hagyomány félreértése folytán."),
    E("ENG", "1.440", "as a result of their misunderstanding of events.", "as a result of their misunderstanding of a transmitted report."),
    E("HUN", "1.444", "hiszen a Szunna tudósa már szólt annak értelméről.", "hiszen a Szunna tudósai bírálták annak értelmét."),
    E("ENG", "1.444", "since the scholar of the Sunnah had spoken about its meaning.", "since the scholars of the Sunnah have criticized its meaning."),
    E("HUN", "1.452a", "„Allah Küldötte (ﷺ) belépett Milhan leányának házába. Lefeküdt és aludt. Majd felnevetett.", "„Allah Küldötte (ﷺ) belépett Umm Ḥarām bint Milḥānhoz. Leheveredett nála, majd felnevetett."),
    E("ENG", "1.452a", "\"The Messenger of Allāh (ﷺ) entered the house of Milhan's daughter. He lay down and slept. Then he laughed.", "\"The Messenger of Allāh (ﷺ) entered upon Umm Ḥarām bint Milḥān. He reclined at her place, then he laughed."),
    E("HUN", "1.452b", "Azt mondta: »Népemből való embereket láttam, amint a kék tengeren hajóznak Allah (ﷻ) útján, mint trónusokon ülő királyok.«", "Azt mondta: »Népemből való emberek, akik a zöld tengeren hajóznak Allah (ﷻ) útján, mint trónusokon ülő királyok.«"),
    E("ENG", "1.452b", "He said: 'I saw people from my Ummah sailing across blue sea in the path of Allāh (ﷻ) as if they were kings seated on thrones.", "He said: \"People from my Ummah, sailing across the green sea in the path of Allāh (ﷻ), like kings seated on thrones.\""),
    E("HUN", "1.452c", "Majd újra elaludt, és felnevetett. A nő megkérdezte az okát, és ő ugyanúgy elmondta álmát, mint korábban.", "Majd ismét felnevetett. A nő megkérdezte az okát, és ő ugyanazt mondta neki, mint korábban."),
    E("ENG", "1.452c", "Then he slept again, and he laughed. She asked him the reason and he repeated his dream as before.", "Then he laughed again. She asked him the reason and he told her the same as before."),
    E("HUN", "1.478", "elláttuk a betegeket, és a sebesülteket Medinába vittük\"", "elláttuk a sebesülteket, és a halottakat visszavittük Medinába\""),
    E("ENG", "1.478", "attending the sick and removing the wounded to Madīna,\"", "treating the wounded and bringing the dead back to Madīnah,\""),
    E("HUN", "1.484", "börtönökhöz és kastélyokhoz folyamodtak", "a bezáráshoz és az elzáráshoz folyamodtak"),
    E("ENG", "1.484", "resorted to prisons and castles", "resorted to imprisonment and confinement"),
    E("HUN", "1.496", "Ami nyilvános életét illeti: Küldöttként (ﷺ) átadta az Üzenetet Allahtól (ﷻ), nevelte a hívőket, ellenállt a hitetleneknek, és kitartott da'wája terjesztésében, míg az gyümölcsöt nem hozott a földkerekség minden szegletében.",
      "Ami nyilvános életét illeti — ahogyan Küldöttként (ﷺ) átadta az Üzenetet Allahtól (ﷻ), nevelte a hívőket, ellenállt a hitetleneknek, és kitartott da'wája terjesztésében, míg az gyümölcsöt nem hozott a földkerekség minden szegletében —, kétségtelen, hogy annak alapja és épülete a hatalmas Korán."),
    E("ENG", "1.496", "As for his public life, as a Messenger (ﷺ) conveying the Message from Allāh (ﷻ), training the believers, resisting the unbelievers and persisting in the spread of his da'wah until it bore fruit in all corners of the globe.",
      "As for his public life — as a Messenger (ﷺ) conveying the Message from Allāh (ﷻ), training the believers, resisting the unbelievers and persisting in the spread of his da'wah until it bore fruit in all corners of the globe — there is no doubt that the mighty Qur'ān is its foundation and its edifice."),
    E("HUN", "1.498", "Semmi kétség: a Korán csodálatos könyv, amely felébreszti az emberi nem magasabb képességeit.", "Bár a Korán csodatévő (mu'jiz) könyv, mégis az emberi nem magasabb képességeinek felébresztésére épül."),
    E("ENG", "1.498", "There is no doubt that, the Qur'ān is a miraculous book, it awakens the higher faculties in the human race.", "Although the Qur'ān is a miraculous book, it works by awakening the higher faculties in the human race."),
    E("HUN", "1.502", "\nÍrás, amelynek Āyāt-jai (versei) kifejtettek: arab nyelvű olvasmány (Korán) tudással bíró embereknek. (Korán 41: 3)", "\n(Írás, amelynek Āyāt-jai (versei) kifejtettek: arab nyelvű olvasmány (Korán) tudással bíró embereknek.) (Korán 41: 3)"),
    E("ENG", "1.502", "\nA Scripture whereof the Āyāt (verses) are expounded, a lecture (Qur'ān) in Arabic for people who have knowledge. (Qur'ān 41: 3)", "\n(A Scripture whereof the Āyāt (verses) are expounded, a lecture (Qur'ān) in Arabic for people who have knowledge.) (Qur'ān 41: 3)"),
    E("HUN", "1.506", "aközött, ahogyan a Korán nevelte az arabokat és ahogyan a Tóra nevelte a zsidókat,", "aközött, ahogyan a Korán terelte az arabokat, és ahogyan a zsidókat a föléjük emelt hegy terelte,"),
    E("ENG", "1.506", "between the education of the Arabs by the Qur'ān and the education of the Jews by the Torah", "between the guidance of the Arabs by the Qur'ān and the guidance of the Jews by the mountain raised over them"),
    E("HUN", "1.508", HUN_RAW_OLD, HUN_RAW_NEW),
    E("ENG", "1.508", ENG_RAW_OLD, ENG_RAW_NEW),
    E("HUN", "1.524", "és egy maroknyi földön küzdöttek.", "és a föld minden araszáért küzdöttek."),
    E("ENG", "1.524", "and they struggled on a handful of earth.", "and they struggled for every span of land."),
    E("HUN", "1.530", "A Próféta (ﷺ) súlyos próbának vettetett alá, hogy képes-e megmenteni a helyzetet:", "A Próféta (ﷺ) hősiesen küzdött, hogy megmentse a helyzetet:"),
    E("ENG", "1.530", "The Prophet (ﷺ) was severely tested in his ability to save the situation:", "The Prophet (ﷺ) fought valiantly to save the situation:"),
    E("HUN", "1.558", "(És Medina városának népe között", "(És a körülöttetek élő beduinok között is vannak képmutatók, és Medina városának népe között"),
    E("ENG", "1.558", "(And among the town people of Al Madīnah", "(And among the wandering Arabs around you there are hypocrites, and among the town people of Al Madīnah"),
    E("HUN", "1.574", "»Hová lesznek akkor a (Tayy) törzs(ének) házai, akik magas rangra jutottak a földön?«", "»Hol lesznek akkor Ṭayyi' rablói, akik lángba borították az országot?«"),
    E("ENG", "1.574", "\"So where will be the homes of (the tribe of) Tayy who have become high ranking in the land?\"", "\"So where will the robbers of (the tribe of) Ṭayyi' be, who have set the land ablaze?\""),
    E("HUN", "1.588a", "Ehhez hasonlók az üldöztetésre figyelmeztető hadíszok.", "Ehhez hasonlók a megpróbáltatásokra (fitan) figyelmeztető hadíszok."),
    E("ENG", "1.588a", "Similar to that are the ḥadīths which warn of persecution.", "Similar to that are the ḥadīths which warn of trials (fitan)."),
    E("HUN", "1.588b", "„Al Alma'ī, aki úgy gyanakszik rád, mintha valóban látott és hallott volna!\"", "„Az éles eszű, aki úgy vélekedik rólad, mintha már látott és hallott volna!\""),
    E("ENG", "1.588b", "\"Al Alma'ī who is suspicious of you as if he actually saw and heard!\"", "\"The sharp-witted man, who judges you as though he had already seen and heard!\""),
    E("HUN", "1.592a", "és várhat-e jégvihart az utazó az egyenlítői vidékeken?", "és lehet-e, hogy az egyenlítői vidékeken járó utazó ne számítson perzselő hőségviharokra?"),
    E("ENG", "1.592a", "or is it possible for a traveller in the equatorial regions to expect a hailstorm?", "or for a traveller in the equatorial regions not to expect scorching storms?"),
    E("HUN", "1.592b", "hogy megfeledkezzék az üldöztetésről, amely tanításait és követőit éri majd", "hogy megfeledkezzék a megpróbáltatásokról, amelyek tanításait és követőit érik majd"),
    E("ENG", "1.592b", "to forget the persecution which affected his teachings and his followers", "to forget the trials which would afflict his teachings and his followers"),
    E("HUN", "1.594", "Ezért beszélt a Próféta (ﷺ) sokat az üldöztetésről; célja nem a megjövendölése volt, hanem az ellene való intés. Szenvedés éri majd az embereket eltérő gondolkodásmódjuk és különböző személyiségük miatt; szenvedés támad, mert a világi élvezetek vonzzák majd az embereket, akik vetélkednek értük; és szenvedés éri az ummát,",
      "Ezért beszélt a Próféta (ﷺ) sokat a megpróbáltatásokról; célja nem a megjövendölésük volt, hanem az ellenük való intés. Megpróbáltatás éri majd az embereket eltérő gondolkodásmódjuk és különböző személyiségük miatt; megpróbáltatás támad, mert a világi élvezetek vonzzák majd az embereket, akik vetélkednek értük; és megpróbáltatás éri az ummát,"),
    E("ENG", "1.594", "Thus the Prophet (ﷺ) talked much about persecution, and his aim was not to prophesy it but to caution against it, suffering will affect people because of their different ways of thinking and their different personalities; suffering will occur because worldly pleasures will attract people who will rival one another for them; and suffering will affect the Ummah",
      "Thus the Prophet (ﷺ) talked much about trials, and his aim was not to prophesy them but to caution against them. Trials will afflict people because of their different ways of thinking and their different personalities; trials will arise because worldly pleasures will attract people who will rival one another for them; and trials will afflict the Ummah"),
    E("HUN", "1.596", "E szenvedések legsúlyosabbika", "E megpróbáltatások legsúlyosabbika"),
    E("ENG", "1.596", "The gravest of all these sufferings", "The gravest of all these trials"),
    E("HUN", "1.606", "tele áhítatot keltő zsivajjal és zsongással.", "tele visszatetsző kiabálással és zavart mormolással."),
    E("ENG", "1.606", "full of awe-inspiring clamouring and droning.", "full of reprehensible shouting and bewildered murmuring."),
    # footnotes
    E("HUN", "1.f5", "Ez az idézet ezért gyenge. Ugyanígy közli Al-Khatīb is, kivéve Rāshid változatát, aki Al Zuhritól közölte, és 'Abdullāh ibn 'Umar ibn 'Urwa meg 'Umar (رضي الله عنه) említésével kapcsolta össze. Ez a közlés azonban ritka, amint azt maga Al-Khatīb kifejtette.",
      "Ez a hagyomány ezért megszakadt (munqaṭi') és gyenge. Ugyanígy közli Al-Khaṭīb is a Taqyīd al-'Ilmben, több láncon 'Urwától, kivéve Rāshid változatát, aki Al-Zuhrītól, 'Urwától közölte, és összefüggővé tette azzal, hogy 'Abdullāh ibn 'Umart említette 'Urwa és 'Umar (رضي الله عنه) között. Ez a változat azonban rendellenes (shādh), amint arra maga Al-Khaṭīb is utalt."),
    E("ENG", "1.f5", "This quotation is therefore weak. It is reported in the same manner by Al-Khatīb with the exception of the version of Rāshid who reported it from Al Zuhri and connected it by mentioning 'Abdullāh ibn 'Umar ibn 'Urwa and 'Umar (رضي الله عنه). However, this report is rare, as Al-Khatīb himself explained.",
      "This report is therefore broken (munqaṭi') and weak. It is reported in the same manner by Al-Khaṭīb in Taqyīd al-'Ilm through several chains from 'Urwa, with the exception of the version of Rāshid, who reported it from Al-Zuhrī from 'Urwa and made it connected by mentioning 'Abdullāh ibn 'Umar between 'Urwa and 'Umar (رضي الله عنه). However, this version is anomalous (shādh), as Al-Khaṭīb himself indicated."),
    E("HUN", "1.f11a", "„Nabhan, Umm Salmah szolgája közölte Umm Salāmától, hogy az ezt mondta: »A Prófétánál (ﷺ) voltam, akárcsak Maimūna,", "„Nabhān, Umm Salamah szabadosa közölte Umm Salamahtól, hogy az ezt mondta: »A Prófétánál (ﷺ) voltam, akárcsak Maymūnah,"),
    E("ENG", "1.f11a", "\"Nabhan, slave of Umm Salmah, reported from Umm Salāmah that she said: \"I was with the Prophet (ﷺ) and so was Maimūna", "\"Nabhān, freedman of Umm Salamah, reported from Umm Salamah that she said: \"I was with the Prophet (ﷺ) and so was Maymūnah"),
    E("HUN", "1.f11b", "„Elfogadható, ha megvizsgálják.\" Csakhogy e hadísz tekintetében semmiféle vizsgálat nem történt vele kapcsolatban.", "„Elfogadható\" — tudniillik megerősítés esetén; e hadísz esetében azonban nincs, aki megerősítené."),
    E("ENG", "1.f11b", "\"Acceptable when scrutinized. But no scrutiny was done of him as regards this Ḥadīth.", "\"Acceptable\", i.e. when corroborated — but he has no corroborator for this Ḥadīth."),
    E("HUN", "1.f11c", "és ez a hadísza ismeretlen\"", "és ez a hadísza elutasított (munkar)\""),
    E("ENG", "1.f11c", "and this Ḥadīth of his is unknown\"", "and this Ḥadīth of his is munkar (rejected)\""),
    E("HUN", "1.f19", "Ismerhetné-e ezt a pontos időmeghatározást bármely „szakértő\", ha Allah (ﷻ) nem adta volna meg neki azt a tudást?", "Ismerhetné-e bárki ezt a pontos időmeghatározást másként, mint a „Szakértő\" — a Kegyes, a Mindenről Értesült (al-Laṭīf al-Khabīr), magasztaltassék — tájékoztatása révén?"),
    E("ENG", "1.f19", "Could this precise temporal definition be known by any \"expert\" if Allāh (ﷻ) did not grant him that information?", "Could this precise timing be known except through the informing of \"the Expert\" — the Subtle, the All-Aware (al-Laṭīf al-Khabīr), glorified and exalted is He?"),
    # tie the body's «خبير» to al-Albānī's pun in fn19
    E("HUN", "1.588c", "Aki ismeri a piac erőit, az a fennálló viszonyok", "A piacok szakértője a fennálló viszonyok"),
    E("HUN", "1.588d", "Aki bensőségesen érti a lélektant, az egyetlen", "A lelkek rejtekeinek szakértője egyetlen"),
    E("HUN", "1.590", "Mohamed (ﷺ) mélyen ismerte az embereket és tulajdonságaikat,", "Mohamed (ﷺ) avatott szakértője volt az emberi lelkeknek és tulajdonságaiknak,"),
    E("ENG", "1.588c", "A person who knows the market forces will not hesitate", "An expert on markets will not hesitate"),
    E("ENG", "1.588d", "Someone who intimately understands psychology will", "An expert on the secrets of souls will"),
    E("ENG", "1.590", "Muhammad (ﷺ) had a deep knowledge of people and their qualities,", "Muhammad (ﷺ) was an expert on people and their qualities,"),
]
