# Ch2 text fixes (no footnote renumbering) — see opus55-findings.md "Ch2"
from apply import E

EDITS = [
    E("HUN", "2.687a", "„A bennünket sújtó idők viszontagságai miatt minden csapásnak ellenállunk, nehogy szégyenbe essünk.\" Némelyikük semmi szégyellnivalót nem talál abban, hogy szegénységét kihirdesse, vagy körülményeit ismertté tegye.",
      "„Az idők ránk nehezedő viszontagságai ellenére is megküzdünk a csapásokkal, mert irtózunk a szégyentől.\" Némelyek szégyellik kimondani szegénységüket és feltárni helyzetüket."),
    E("ENG", "2.687a", "\"Because of the vicissitudes of time which affect us, we resist any calamities for fear of being disgraced. Some of them may find nothing shameful in announcing their poverty or letting their circumstances be known.",
      "\"In spite of the biting vicissitudes of time upon us, we grapple with calamities out of loathing for disgrace.\" Some people may find it embarrassing to announce their poverty or to let their circumstances be known."),
    E("HUN", "2.691", "A karaván betegségének hírével jött meg, és nem sokkal később jött halálának híre.", "A karaván az ő betegségének hírével tért vissza, és nem sokkal később jött halálának híre."),
    E("HUN", "2.695", "Születésének dátumát Rabi'i al Awwal 12-ére teszik, a hidzsra előtti (Kr. e. — BH) 53. évben.", "Születésének dátumát Rabī' al-Awwal 12-ére teszik, a hidzsra előtti 53. évben."),
    E("ENG", "2.695", "The date of his birth is set at 12 Rabi'i al Awwal 53 BH, that is, before the Hijra.", "The date of his birth is set at 12 Rabī' al-Awwal 53 BH, that is, before the Hijrah."),
    E("HUN", "2.697", "semmi közük a sarī'ához.", "semmi közük a saríához."),
    E("HUN", "2.721", "(És sugallatot adtunk Mózes anyjának.) (Korán 28: 7)", "(És sugallatot adtunk Mózes anyjának: „Szoptasd őt…\") (Korán 28: 7)"),
    E("ENG", "2.721", "(And We inspired the mother of Moses.) (Qur'ān 28: 7)", "(And We inspired the mother of Moses, saying: Suckle him…) (Qur'ān 28: 7)"),
    E("HUN", "2.723", "Mohamednek (ﷺ) semmi szüksége minderre; az a nagy szerep, amelyet most, a mi korunkban játszik, kevésre becsülteti velünk az ilyen meséket.", "Mohamednek (ﷺ) semmi szüksége minderre: a dicső valóságból rá eső hatalmas rész elég ahhoz, hogy kevésre becsüljük az ilyen meséket."),
    E("ENG", "2.723", "Muhammad (ﷺ) is not in need of any of this, the great role that he plays now in our present age makes us think little of such tales.", "Muhammad (ﷺ) is not in need of any of this: his huge share of honourable reality makes us indifferent to such tales."),
    E("HUN", "2.725", "— e nevet valószínűleg nemes angyal sugallta!", "— e névadásban nemes angyal segítette!"),
    E("ENG", "2.725", "a name probably inspired by a noble angel!", "a naming in which a noble angel helped him!"),
    E("HUN", "2.735", "Amíg Ya'qūb élt, gondoskodtak róla. Megérte az öregkort, tapasztalatra és bölcsességre tett szert. Sőt, megadatott neki a prófétaság. Egy nap körülnézett, és nem látta maga mellett Yūsufot (عليه السلام):",
      "Ya'qūb élt és virult; megvolt az öregkora, tapasztalata és bölcsessége — mégis egy napon körülnézett, és nem látta maga mellett Yūsufot (عليه السلام):"),
    E("ENG", "2.735", "While Ya'qūb was alive he was provided for. He reached old age and acquired experience and wisdom. In fact, he was granted prophethood. One day he looked round and did not see Yūsuf (عليه السلام) next to him:",
      "Ya'qūb was alive and well; he had his old age, his experience and his wisdom — yet one day he looked round and did not see Yūsuf (عليه السلام) next to him:"),
    E("HUN", "2.751", "Azután megmosta őt egy aranyból készült tálban a Zamzam vizével. Majd lezárta mellkasát, és visszavitte oda, ahol volt.", "Azután megmosta a szívet egy aranyból készült tálban a Zamzam vizével, majd visszahelyezte a helyére."),
    E("ENG", "2.751", "Then he washed him in a basin made of gold with the water of Zamzam. Then he sealed his chest and returned him to where he was.", "Then he washed it (the heart) in a basin made of gold with the water of Zamzam, then returned it to its place."),
    E("HUN", "2.755", "„Miközben Al Hatīmban voltam — talán azt mondta: Al Hajrban —", "„Miközben Al-Ḥaṭīmban voltam — talán azt mondta: Al-Ḥijrben —"),
    E("ENG", "2.755", "\"While I was in Al Hatīm perhaps he said in Al Hajr reclining", "\"While I was in Al-Ḥaṭīm — perhaps he said in Al-Ḥijr — reclining"),
    E("HUN", "2.759", "a Próféták (ﷺ) szíve, Allah róluk való gondoskodása által", "a próféták szíve, Allah (ﷻ) róluk való gondoskodása által"),
    E("HUN", "2.795", "és Saudának volt a leghosszabb keze.", "és Sawdának volt a leghosszabb keze."),
    E("ENG", "2.795", "and it was Saudah who had the longest hand.", "and it was Sawdah who had the longest hand."),
    E("HUN", "2.797", "szolgálóját, Umm Aimant.", "szolgálóját, Umm Aymant."),
    E("ENG", "2.797", "her maid Umm Aiman.", "her maid Umm Ayman."),
    E("HUN", "2.799", "Ghazában halt meg,", "Gázában halt meg,"),
    E("ENG", "2.799", "He died in Ghaza and", "He died in Gaza and"),
    E("HUN", "2.807", "Ez az ember arcán és hátán meglátta a prófétaság jeleit.", "Ez az ember arcán és a két válla között meglátta a prófétaság jeleit."),
    E("ENG", "2.807", "This man saw in his face and on his back the signs of prophethood.", "This man saw in his face and between his shoulders the signs of prophethood."),
    E("HUN", "2.853", "éberség az ő védelmükre.\n\nTalán ez szoktatta őket az emberek vezetéséhez: gyöngédség a gyengék iránt, és éberség az ő védelmükre.\n", "éberség az ő védelmükre.\n"),
    E("HUN", "2.865", "amikor ugyanezeket a problémákat az utca emberei elé tárták, akiknek természete és ítélőképessége szeplőtelen maradt, azonnal fején találták a szöget.", "amikor ugyanezeket a problémákat egy írástudatlan ember elé tárták, akinek természete ép és értelme tiszta maradt, az azonnal fején találta a szöget."),
    E("ENG", "2.865", "when these same problems are presented to people in the street who remain unblemished in their nature and reasoning, they immediately hit the nail on the head.", "when these same problems are presented to an unlettered man whose nature and reason remain unblemished, he immediately hits the nail on the head."),
    E("HUN", "2.943", "Azonban csodálata a tesztelt férfi iránt ennél jóval mélyebb volt.", "Csodálata azonban a férfi iránt, akit így próbára tett, ennél jóval mélyebb volt."),
    E("HUN", "2.945", "Mindent átadott, ami nála volt, és jól elégedetten, másoktól is elégedetten távozott.", "Teljesítette, amivel tartozott, majd elégedetten és megbecsülten távozott."),
    E("HUN", "2.955a", "Először Al Qāsimt szülte, ez az a melléknév (kunya), amelyen a próféta korában ismerték. Aztán jöttek Zaynab, Ruqayyah, Umm Kulthūm, Fāṭimah és 'Abdullah, akit Ṭāhirnak is hívnak.",
      "Először Al-Qāsimot szülte — róla kapta kunyáját (Abū al-Qāsim), amelyen a prófétaság után szólították. Aztán jöttek Zaynab, Ruqayyah, Umm Kulthūm, Fāṭimah és 'Abdullāh, akit al-Ṭayyibnak és al-Ṭāhirnak is neveztek."),
    E("ENG", "2.955a", "and this is the Kunniya by which he was known in the era of prophethood. Then came Zaynab, Ruqayyah, Umm Kulthūm, Fātimah and Abdullāh, who is also known as Tāhir.",
      "after whom he was given his Kunyah (Abū al-Qāsim) after prophethood. Then came Zaynab, Ruqayyah, Umm Kulthūm, Fātimah and 'Abdullāh, who was also called al-Ṭayyib and al-Ṭāhir."),
    E("HUN", "2.955b", "és kétségtelen, hogy ezt a házat megérintette urának szelleme;", "és kétségtelen, hogy ezt az új otthont áthatotta a ház urának szelleme;"),
    E("HUN", "2.957", "Egy könnyelű embercsoportban élő okos ember", "Egy könnyelmű embercsoportban élő értelmes ember"),
    E("HUN", "2.959", "kivéve az a tény, hogy Khadījah búslakodott", "kivéve azt, hogy Khadījah búslakodott"),
    E("HUN", "2.961", "„Amit mi teszünk, tartósabb, mint amit az amputált Ṣunbur tesz.\" A Ṣunbur egy olyan datolyapálma, amelynek gyökerei töröttek.", "„Ami a mi utunk, igazabb annál, amit ez a csonka ṣunbūr követ.\" A ṣunbūr olyan datolyapálma, amelynek gyökere eltört."),
    E("ENG", "2.961", "'What we are doing is more lasting than what the amputated Sunbūr is doing.\" The Sunbūr is a date palm whose roots are broken.", "\"What we follow is more rightful than what this cut-off ṣunbūr follows.\" The ṣunbūr is a date palm whose root is broken."),
    E("HUN", "2.1009", "Zayd ibn 'Amr ibn Nufayllal az alsó Baldahban,", "Zayd ibn 'Amr ibn Nufayllal az alsó Baldaḥban,"),
    E("HUN", "2.1023", "Ezek a viták erőszakos háborúkhoz vezetve egymás között, és szektákra osztva őket – amelyek mindegyike átkozta a többit. A szíriai keresztények, akiket Zayd (رضي الله عنه) megkérdezett, Jakobiták voltak, és különböztek a Római Katolikus Egyház hivatalos hitvallásától. Így nem volt meglepő, hogy Zaydnak (رضي الله عنه) szólnak az átkokról, amelyek rá hárulnának, ha belépne vallásukba.",
      "Ezek a viták pusztító háborúkat szítottak közöttük, és szektákra szakították őket, amelyek egymást átkozták. A szíriai keresztények, akiket Zayd (رضي الله عنه) megkérdezett, jakobiták voltak, és eltértek a római egyház hivatalos hitvallásától. Így nem meglepő, hogy tudatták Zayddal (رضي الله عنه), milyen gyötrelem várna rá, ha belépne vallásukba."),
    E("HUN", "2.1029", "igazságtalanságait, hálásak voltak az igazság meglátásának képességéért, és nem becsülték alá értéküket a társadalmukban. A sors azonban kiválasztott egy olyan embert, aki megérezte az igazságot, és rendelkezett azzal a képességgel, hogy az egész világ minden részébe elterjeszsze",
      "igazságtalanságait; köszönet illeti őt az igazság kereséséért, és sem tőle, sem a többiektől nem vitatható el a népük körében kivívott megbecsülés. A sors azonban kiválasztott egy olyan embert, aki megérezte az igazságot, és rendelkezett azzal a képességgel, hogy az egész világ minden részébe elterjessze"),
    E("ENG", "2.1029", ", were thankful for their ability to see the truth and did not underestimate their value in their society.", "; he deserves thanks for his search for the truth, and neither he nor the others should be denied their standing among their people."),
    E("HUN", "2.1033", "egy modern világ tudósának véleményéhez", "egy mai csillagász véleményéhez"),
    E("ENG", "2.1033", "the opinion of scientist of a modern world towards", "the opinion of an astronomer of our time towards"),
    E("HUN", "2.1035", "Ez volt az elmei oldal.", "Ez volt az értelmi oldal."),
    E("HUN", "2.1041", "Előtte a sivatag tanúja volt egy testvérének, aki Egyiptomból menekülve jött, és száraz, kopár vidékeken kelt át, önmagának és népének békét, biztonságot és útmutatást keresve. Vonzotta a völgy jobb oldalán lévő égő bokor látványa, és amikor odament,",
      "Előtte a sivatag tanúja volt egy testvérének — Mūsānak (عليه السلام) —, aki Egyiptomból menekülve jött, és száraz, kopár vidékeken kelt át, önmagának és népének békét, biztonságot és útmutatást keresve. A völgy jobb partján vigasztaló tűz villant fel előtte, és amikor odament,"),
    E("ENG", "2.1041", "Before him the desert had witnessed a brother of his who came in flight from Egypt, and traversed the dry, barren lands, seeking peace, security and guidance for himself and his people. He was attracted by the sight of a burning bush on the right hand side of the valley, and when he went toward it,",
      "Before him the desert had witnessed a brother of his — Moses (عليه السلام) — who came in flight from Egypt, and traversed the dry, barren lands, seeking peace, security and guidance for himself and his people. A comforting fire flashed before him from the right bank of the valley, and when he went toward it,"),
    E("HUN", "2.1059", "új teremménnyé teszi", "új teremtménnyé teszi"),
    E("HUN", "2.1065", "Az a messzeható változás megtörtént – ez volt a prófécia! Milyen csodálatos volt a jövő áldás, és milyen nagy gondok elé nézett Mohamed (ﷺ) az ő képviseletében.",
      "Az a messzeható változás megtörtént – ez volt a prófétaság! Milyen fenséges volt ez az érkező kegy, és mekkora feladatok és gondok vártak benne Mohamedre (ﷺ)!"),
    E("ENG", "2.1065", "How wonderful was the coming blessing and how great were the anxieties Muhammad (ﷺ) would have to face on its behalf.", "How sublime was this approaching grace, and how great were the tasks and anxieties Muhammad (ﷺ) would have to face in it!"),
    # footnotes (numbers < 12, or number-free anchors)
    E("HUN", "2.f1", "Wā'ilah ibn Al Asqa' tekintélyére", "Wāthilah ibn al-Asqa' tekintélyére"),
    E("ENG", "2.f1", "Wa'ila ibn Al Asqa'", "Wāthilah ibn al-Asqa'"),
    E("HUN", "2.f3", "Qaṣīdat al-Burdahjáról (Fordító).", "Qaṣīdat al-Burdahjáról (az angol fordító)."),
    E("HUN", "2.f5", "amikor a Prófétáról (ﷺ) beszélt (Fordító).", "amikor a Prófétáról (ﷺ) beszélt (az angol fordító)."),
    E("HUN", "2.f13", "Ibn 'Abdul Barr eldöntetlenül (mu'allaq) hagyta a Jāmi' Bayān al-'Ilmban;", "Ibn 'Abdul Barr lánc nélkül (mu'allaq) idézte a Jāmi' Bayān al-'Ilmban;"),
]
