# Ch3 part 3 (Ṭā'if → A Quraish és az Isrā') + ch1 book-title unification — see opus55-findings.md "Ch3 part 3"
from apply import E

HUN_HAYKAL = "\n\nDr. Haykal azt mondja: „Úgy vélem, ha azokat kérdeznéd erről, akik szerint az Isrā' a lélekkel történt, semmi csodálatosat nem látnának benne, azok után, amit a tudomány korunkban megismert a hipnózis lehetőségéről, amelynek révén távoli helyeken lévő dolgokról lehet beszélni. Hát még egy olyan lélek, amely magában foglalja a világegyetem egész lelki életének egységét, és — az Allahtól kapott erő révén — kapcsolatba tud lépni az élet titkával a világegyetem kezdetétől a végéig!\""
ENG_HAYKAL = "\n\nDr. Haykal says: \"I think that if you asked those who hold that the Isrā' was by the spirit alone about this, they would see nothing marvellous in it, after what science has learnt in our time of the possibility of hypnosis enabling one to speak of things located in distant places. How much more so a spirit which unites in itself the whole spiritual life of the universe, and which can — by the power Allāh has granted it — make contact with the secret of life from the beginning of the universe to its end!\""

EDITS = [
    E("HUN", "3.1673", "[azaz Gábriel angyalt]", "[azaz Jibrīl angyalt]"),
    E("ENG", "3.1673", "[that is, the Angel Gabriel]", "[that is, the Angel Jibrīl]"),
    E("HUN", "3.1703", "próféta-testvéreit a Mecsetben.", "próféta-testvéreit a Legtávolabbi Mecsetben (al-Aqṣā)."),
    E("ENG", "3.1703", "his brother prophets in two rak'ahs of prayer in the Mosque.", "his brother prophets in two rak'ahs of prayer in the Farthest Mosque (al-Aqṣā)."),
    E("HUN", "3.1705", "Ő a számára elrendelt időben jött el, amely a legalkalmasabb volt.", "Ez a feltárás azonban a maga alkalmas idejében történt."),
    E("ENG", "3.1705", "He came at the time which was ordained for him and which was the most suitable.", "This disclosure, however, came at its fitting time."),
    E("HUN", "3.1715", "a Nílust és az Eufráteszt az egekben látta.", "a Nílust és az Eufráteszt a Paradicsomban látta."),
    E("ENG", "3.1715", "his seeing the Nile and the Euphrates in the heavens. It does not mean that the waters of these two rivers spring from Heaven,", "his seeing the Nile and the Euphrates in Paradise. It does not mean that the waters of these two rivers spring from Paradise,"),
    E("HUN", "3.1753", "a korai próféciák folytatásának", "a korábbi prófétaságok folytatásának"),
    E("ENG", "3.1753", "a continuation of the early prophecies", "a continuation of the earlier prophethoods"),
    E("HUN", "3.1761", "A romlott természet olyan, mint a kötőhártya-gyulladástól fertőzött szem, amely gennyként üríti a tisztátalanságokat. Bár ezek a tisztátalanságok élénk színű takaró alá rejthetők, és az emberek megtéveszthetők vele, az emberek Ura soha nem téveszthető meg.",
      "A romlott természet olyan, mint a fekete iszapos forrás: nem folyik belőle más, csak szenny és feketeség. Ezt az undorító feketeséget olykor élénk színek és cicomás látszat mögé rejtik."),
    E("ENG", "3.1761", "A corrupt nature is like an eye infected with conjunctivitis which discharges impurities as pus. Although these impurities may be hidden under a brightly coloured covering and people may be deceived by it, the Lord of men will never be deceived.",
      "A corrupt nature is like a spring of black mud from which nothing flows but filth and blackness. This loathsome blackness may at times be hidden behind bright colours and embellished appearances."),
    E("HUN", "3.1763", "a gonosz bűnök legalacsonyabb fokának számítanak majd.", "még a nyílt, gonosz bűnöknél is alábbvalónak számítanak."),
    E("ENG", "3.1763", "they will be considered the lowest grade of wicked sins.", "they are considered even lower in rank than flagrant, wicked sins."),
    E("HUN", "3.1771", "Az ima segít azokon az embereken is, akiknek szíve halott — jóllehet mindig létezni fognak, míg szívük újjá nem éled, vagy a földbe nem temettetnek.",
      "Akiknek pedig halott a szívük, azokon az ima semmit sem segít — és így is maradnak, míg szívük újjá nem éled, vagy a föld be nem takarja őket."),
    E("ENG", "3.1771", "Prayer will help people whose hearts are dead, although they will always remain in existence until their hearts are revived or they are buried in the earth.",
      "As for those whose hearts are dead, prayer avails them nothing at all — and so they will remain until their hearts are revived or the earth covers them."),
    E("HUN", "3.1781", "„Amikor a Quraish meghazudtolt, elkezdtem leírni nekik, úgy, ahogyan néztem!\"³³", "„Amikor a Quraish meghazudtolt, a Ḥijrben álltam, és Allah (ﷻ) feltárta előttem Jeruzsálemet (Bayt al-Maqdis); elkezdtem hát leírni nekik jeleit, miközben néztem!\"³³" + HUN_HAYKAL),
    E("ENG", "3.1781", "\"When the Quraish denounced me, I began describing it as I had watched it!\"³³", "\"When the Quraish denied me, I stood in the Ḥijr, and Allāh (ﷻ) displayed Jerusalem (Bayt al-Maqdis) before me, so I began describing its features to them while I was looking at it!\"³³" + ENG_HAYKAL),
    E("HUN", "3.1785", "Dr. Haikal még hozzáteszi", "Dr. Haykal még hozzáteszi"),
    E("ENG", "3.1785", "Dr Haikal even adds", "Dr. Haykal even adds"),
    E("HUN", "3.1793", "Ha egy férfi messziről tért vissza törzséhez, e szavakkal fogadták: „Óvakodj a Quraish-beli férfitól, nehogy tévútra vigyen.\"", "Aki messzi vidékekről érkezett, azt népe ezzel az intelemmel bocsátotta útra: „Óvakodj a Quraish ifjától, nehogy elcsábítson!\""),
    E("ENG", "3.1793", "A man would return to his tribe from afar and be received by them with these words: \"Beware of the man from the Quraish lest he misguide you.\"", "A man coming from distant parts would be sent off by his people with this advice: \"Beware of the youth of Quraish lest he seduce you!\""),
    E("ENG", "3.1793b", "'Abs, Ba nu al Naḍr,", "'Abs, Banu al Naḍr,"),
    E("HUN", "3.f11", "¹¹ Az elbeszélő, Ja'far ibn 'Abdullāh ibn Abī al-Ḥakam a Dūs törzs egyik Tābi'ījeként azonosítható, aki Anastól (رضي الله عنه) és a Tābi'īntől beszélt el. Ha ez ugyanaz a személy, a lánc mursal, és ezért gyenge.",
      "¹¹ Nem találtam ezt az elbeszélőt az elbeszélők között; csak Ja'far ibn 'Abdullāh ibn al-Ḥakam szerepel köztük, aki az Aws törzsbeli anṣārī, a Tābi'ūn fiatalabb nemzedékéhez tartozik, és Anastól (رضي الله عنه) meg a Tābi'ūntól hagyományozott. Ha ő az, a lánc mursal, és ezért gyenge; a hozzá vezető láncot nem találtam. Ha pedig más, nem ismerem."),
    E("ENG", "3.f11", "There is Ja'far ibn 'Abdullāh ibn Ḥakam, who is a Tabi'i of the tribe of Dus. He narrated from Anas (رضي الله عنه) and the Tabi'in. if he is this person, then the chain is mursal and therefore weak. I did not encounter this ascription being made to him.",
      "There is only Ja'far ibn 'Abdullāh ibn al-Ḥakam, an Anṣārī of the Aws and a younger Tābi'ī, who narrated from Anas (رضي الله عنه) and the Tābi'ūn. If he is this person, then the chain is mursal and therefore weak; I have not found the chain leading to him."),
    E("HUN", "3.f20", "²⁰ Gyenge hadísz, Isḥāq beszélte el mursalként,", "²⁰ Gyenge hadísz, Ibn Isḥāq beszélte el mursalként,"),
    E("ENG", "3.f20", "²⁰ A weak Ḥadīth narrated by Isḥāq as mursal", "²⁰ A weak Ḥadīth narrated by Ibn Isḥāq as mursal"),
    E("HUN", "3.f22", "„A láncban ott van Ibn Ishāq, aki csaló, de a lánc többi tagja megbízható.\"", "„A láncban ott van Ibn Isḥāq, aki mudallis (tadlīst gyakorol), de a lánc többi tagja megbízható.\""),
    E("ENG", "3.f22", "\"In the chain is Ibn Ishāq and he is a fraud, but the rest of them in the chain are reliable.", "\"In the chain is Ibn Isḥāq and he is a mudallis (practises tadlīs), but the rest of them in the chain are reliable.\""),
    E("HUN", "3.f25", "hogy „ez a Paradicsomból való\", igazat mond", "hogy „ez az égből való\", igazat mond"),
    E("ENG", "3.f25a", "\"this is from Heaven, \"he is telling the truth", "\"this is from the sky\", he is telling the truth"),
    E("ENG", "3.f25b", "that four rivers are from heaven. This means that they were originally from heaven,", "that four rivers are from Paradise. This means that they were originally from Paradise,"),
    E("HUN", "3.f28", "Része a Sa'sa ibn Mālik által az Isrā'ról közölt hadísznak.", "Része a Ṣa'ṣa'ah ibn Mālik [így az arab eredetiben; a hadísz elbeszélője helyesen Mālik ibn Ṣa'ṣa'ah — a ford.] által az Isrā'ról közölt hadísznak."),
    E("ENG", "3.f28", "reported by Sa'sa ibn Mālik on the Isrā'.", "reported by Ṣa'ṣa'ah ibn Mālik [thus in the Arabic original; the narrator is Mālik ibn Ṣa'ṣa'ah — translator's note] on the Isrā'."),
    E("HUN", "3.f30", "Bukhārī és Muszlim beszélte el Abū Hurairah (رضي الله عنه) tekintélyére hivatkozva, és mindketten a „Allah szolgáinak tettei\" fejezetben Jābir (رضي الله عنه) tekintélyére hivatkozva is.",
      "Bukhārī és Muszlim beszélte el Abū Hurairah (رضي الله عنه) tekintélyére hivatkozva; Jābir (رضي الله عنه) hadíszaként pedig Muszlim, valamint Bukhārī az *Af'āl al-'Ibād* (»A szolgák cselekedetei«) című művében."),
    E("ENG", "3.f30", "and also by the two of them in the chapter \"The actions of Allāh's slaves\" on the authority of Jābir (رضي الله عنه).", "and, as a ḥadīth of Jābir (رضي الله عنه), by Muslim, and by Bukhārī in his book *Af'āl al-'Ibād* (\"The Actions of the Servants\")."),
    # book title unification (ch1 fn12/13 ↔ ch3 fn26)
    E("HUN", "1.f12-13", "Lásd A muszlim eszmevilága című könyvemet.", "Lásd *'Aqīdat al-Muslim* (A muszlim hitvallása) című könyvemet.", count=2),
    E("ENG", "1.f12-13", "See my book The Ideology of the Muslim.", "See my book *'Aqīdat al-Muslim* (The Creed of the Muslim).", count=2),
]
