# Ch4 part 1 (A tömeges hidzsra → Dār al-Nadwah) — see opus55-findings.md "Ch4 — part 1"
from apply import E

EDITS = [
    E("HUN", "4.1910a", "és miközben *Al-Aqabánál* volt,", "és miközben *al-'Aqabánál* volt,"),
    E("ENG", "4.1910a", "and while he was at *Al-Aqabah*,", "and while he was at *al-'Aqabah*,"),
    E("HUN", "4.1910b", "'Āṣim ibn 'Umar ibn Qatāda (رضي الله عنه) beszélt nekem", "'Āṣim ibn 'Umar ibn Qatādah beszélt nekem"),
    E("ENG", "4.1910b", "'Āṣim ibn 'Umar ibn Qatāda (رضي الله عنه) spoke to me", "'Āṣim ibn 'Umar ibn Qatādah spoke to me"),
    E("HUN", "4.1924", "nem lesz nálad kedvesebb ember számunkra!\"", "nem lesz nálad hatalmasabb ember!\""),
    E("ENG", "4.1924", "then there will be no man dearer to us than you!\"", "then there will be no man mightier than you!\""),
    E("HUN", "4.1938", "Mus'ab Ibn 'Umayr", "Muṣ'ab ibn 'Umayr", count=2),
    E("ENG", "4.1938", "Mus'ab Ibn 'Umayr", "Muṣ'ab ibn 'Umayr", count=2),
    E("HUN", "4.1962a", "macskaként osonva és rejtőzve,", "pusztai tyúkként (qaṭā) osonva és rejtőzve,"),
    E("ENG", "4.1962a", "slipping away like cats and hiding", "slipping away like sandgrouse and hiding"),
    E("HUN", "4.1962b", "Naseeba bint Ka'b (رضي الله عنها)", "Nusaybah bint Ka'b (رضي الله عنها)"),
    E("ENG", "4.1962b", "Naseeba bint Ka'b (رضي الله عنه)", "Nusaybah bint Ka'b (رضي الله عنها)"),
    E("HUN", "4.1966", "Azt mondta: „Ó, Yathrib népe!", "Azt mondta: „Ó, Khazraj gyülekezete!"),
    E("ENG", "4.1966", "He said: \"O people of Yathrib:", "He said: \"O assembly of the Khazraj:"),
    E("HUN", "4.1974", "al-Barrā' Ibn Ma'rūr kézen fogta", "al-Barā' ibn Ma'rūr kézen fogta"),
    E("ENG", "4.1974", "al-Barrā' Ibn Ma'rūr took him", "al-Barā' ibn Ma'rūr took him"),
    E("HUN", "4.1976", "Abul Haytham ibn al Tahān ekkor", "Abū al-Haytham ibn al-Tayyihān ekkor"),
    E("ENG", "4.1976", "Abul Haytham ibn al Tahān then", "Abū al-Haytham ibn al-Tayyihān then"),
    E("HUN", "4.1978", "„Nem. A vér vér, és a rombolás rombolás.", "„Nem: a ti véretek az én vérem, a ti romlásotok az én romlásom."),
    E("ENG", "4.1978", "\"No, blood is blood and destruction is destruction.", "\"No: your blood is my blood, and your ruin is my ruin."),
    E("HUN", "4.1990", "lerombolt házak és városok nyomát hagyva mögöttük.\n", "lerombolt házak és városok nyomát hagyva mögöttük.\n\n*Elfutottak, s a föld színe átkozta őket, mint hamisság, mely megfutamodik az igazság fensége előtt!!*\n"),
    E("ENG", "4.1990", "leaving behind them a trail of destroyed houses and cities.\n", "leaving behind them a trail of destroyed houses and cities.\n\n*They turned and fled, and the face of the earth cursed them, like falsehood routed by the majesty of the truth!!*\n"),
    E("HUN", "4.1998", "Írd le őket nekünk.\"\n\n„Ők a messzi törzsekből való emberek, akiket nem köt össze közeli vérrokonság; szeretik egymást, és egyetlen sorba kovácsolták magukat Allah tetszéséért.",
      "Írd le őket nekünk.\"\n\nA Próféta (ﷺ) arca felderült a beduin kérdésére, és így szólt: „Ők a messzi törzsekből való emberek, akiket nem köt össze közeli vérrokonság; Allahért szeretik egymást, és tiszta szívvel vannak egymás iránt."),
    E("ENG", "4.1998", "Describe them to us.\"\n\n\"They are the people from far-off tribes, who are not connected by any close blood relationship, love one another, and have bonded themselves into one rank for Allāh's pleasure.",
      "Describe them to us.\"\n\nThe Prophet's (ﷺ) face lit up at the bedouin's question, and he said: \"They are the people from far-off tribes, who are not connected by any close blood relationship; they love one another for Allāh's sake and are sincere towards one another."),
    E("HUN", "4.2004", "Úgy tértek hát nyugovóra, mint a bűnöző, aki elkövette bűnét, és biztos benne, hogy senki sem látta. Valójában ezen az éjszakán",
      "Úgy tértek hát nyugovóra, mint a bűnöző, aki elkövette bűnét, és biztonságban érzi magát a megtorlástól.\n\n*Jó véleményed volt a napokról, amikor jók voltak hozzád, és nem féltél attól a rossztól, amit a végzet hozhat;*\n\n*az éjszakák békén hagytak, és te elbizakodtál bennük — pedig az éjszakák derűjében támad a zavar.*\n\nBizony, ezen az éjszakán"),
    E("ENG", "4.2004", "So they went to sleep like a criminal who has committed a crime and feels sure that no one saw him. Indeed, during this night",
      "So they went to sleep like a criminal who has committed a crime and feels safe from retribution.\n\n*You thought well of the days when they treated you well, and did not fear the evil that fate might bring;*\n\n*the nights left you in peace and you were deceived by them — yet it is in the clear nights that trouble arises.*\n\nYes, during this night"),
    E("HUN", "4.2008", "Sa'd Ibn 'Ubāda (رضي الله عنه) így szólt:", "Sa'd ibn 'Ubādah [így az arab eredetiben; Ibn Isḥāq szerint al-'Abbās ibn 'Ubādah ibn Naḍlah mondta ezt — a ford.] így szólt:"),
    E("ENG", "4.2008", "Sa'd Ibn 'Ubāda (رضي الله عنه) said:", "Sa'd ibn 'Ubādah [thus in the Arabic original; according to Ibn Isḥāq it was al-'Abbās ibn 'Ubādah ibn Naḍlah who said this — translator's note] said:"),
    E("HUN", "4.2016", "Jubayr Ibn Mut'im és Al-Ḥaris Ibn Ḥarb", "Jubayr ibn Muṭ'im és al-Ḥārith ibn Ḥarb"),
    E("ENG", "4.2016", "Jubayr Ibn Mut'im and Al-Ḥaris Ibn Ḥarb", "Jubayr ibn Muṭ'im and al-Ḥārith ibn Ḥarb"),
    E("HUN", "4.2020", "Minden tehetős muszlim kötelességévé vált, hogy segítsen ennek az új hazának a felépítésében, és minden erejét megerősítésére meg a többi nemzet közötti rangjának emelésére fordítsa. Medinát a bevándorlás után elhagyni a felelősség alóli kibúvás lett, és Allah (ﷻ) meg Küldötte (ﷺ) élethosszig tartó elárulása. A hit része volt ez, hiszen a hit megszilárdulása Medina fejlődésén múlt.",
      "Minden erre képes muszlim kötelességévé vált, hogy segítsen ennek az új hazának a felépítésében, és minden erejét megerősítésére meg a többi nemzet közötti rangjának emelésére fordítsa. Medinát a hidzsra után elhagyni az igazság kötelességei alóli kibúvás lett, és Allah (ﷻ) meg Küldötte (ﷺ) támogatásának megtagadása: az ottani élet maga volt a vallás, hiszen a vallás megszilárdulása Medina megerősödésén múlt."),
    E("ENG", "4.2020", "Leaving Madīnah after migration to it became a shirking of responsibility and a betrayal of Allāh (ﷻ) and His Messenger (ﷺ) for life. In it was part of faith, since the establishment of the faith depended upon the development of Madīnah.",
      "Leaving Madīnah after migration to it became a shirking of the duties of the truth and a withholding of support from Allāh (ﷻ) and His Messenger (ﷺ): living there was itself religion, since the establishment of the religion depended upon the strengthening of Madīnah."),
    E("HUN", "4.2032a", "Semmi más ez, mint a hit, amely hegyeket mozgat, és nem céltalan.", "Ez az a hit, amely a hegyeknél is többet nyom a latban, és nem inog meg!"),
    E("ENG", "4.2032a", "It is nothing but faith which moves mountains and is not aimless.", "It is the faith which outweighs mountains and does not waver!"),
    E("HUN", "4.2032b", "Ami a lármás, zavarodott gyávákat illeti,", "Ami a félénk, gyáva és nyugtalan embert illeti,"),
    E("ENG", "4.2032b", "As for the noisy, confused cowards", "As for the timid, faint-hearted and anxious"),
    E("HUN", "4.2038", "'Umar Ibn Rabī'ah (رضي الله عنه) háza előtt,", "'Umar ibn Rabī'ah (رضي الله عنه) [így az arab eredetiben; Ibn Isḥāq szerint a Banū Jaḥsh háza volt, a vak testvér pedig Abū Aḥmad ibn Jaḥsh — a ford.] háza előtt,"),
    E("ENG", "4.2038", "the house of 'Umar Ibn Rabī'ah (رضي الله عنه) after", "the house of 'Umar ibn Rabī'ah (رضي الله عنه) [thus in the Arabic original; according to Ibn Isḥāq it was the house of the Banū Jaḥsh, and the blind brother was Abū Aḥmad ibn Jaḥsh — translator's note] after"),
    E("HUN", "4.2044", "Abū Salma", "Abū Salamah", count=3),
    E("HUN", "4.2050", "Umm Salma", "Umm Salamah", count=2),
    E("ENG", "4.2044", "Abū Salma", "Abū Salamah", count=3),
    E("ENG", "4.2050a", "'Umm Salma", "Umm Salamah", count=1),
    E("ENG", "4.2050b", "Umm Salma ", "Umm Salamah ", count=2),
]
