# Ch5 — see opus55-findings.md "Ch5"
from apply import E

EDITS = [
    E("HUN", "5.2359", "egykor datolyapálmák és magvető fák borították,", "egykor datolyapálmák és gharqad-bokrok borították,"),
    E("ENG", "5.2359", "was once covered with date palms and seeding trees,", "was once covered with date palms and gharqad (boxthorn) trees,"),
    E("HUN", "5.2361a", "A Próféta (ﷺ) megparancsolta, hogy a pálmákat vágják ki, a sírokat pedig egyengessék el.¹", "A Próféta (ﷺ) megparancsolta, hogy a pálmákat vágják ki, a sírokat¹ nyissák fel, a romokat pedig egyengessék el."),
    E("ENG", "5.2361a", "The Prophet (ﷺ) ordered the palms to be cut down and the tombs to be levelled.¹", "The Prophet (ﷺ) ordered the palms to be cut down, the graves¹ to be dug up and the ruins to be levelled."),
    E("HUN", "5.2361b", "és így vidították magukat énekelve: „Ó, Allah (ﷻ), nincs más élet, csak a Túlvilág élete — bocsáss meg hát az anṣāroknak és a muhādzsiroknak!\" A társak",
      "és így vidították magukat énekelve:\n\n*„Ó, Allah (ﷻ), nincs más élet, csak a Túlvilág élete —*\n\n*bocsáss meg hát az anṣāroknak és a muhādzsiroknak!\"*\n\nA társak"),
    E("HUN", "5.2361c", "Egyikük ezt a párverset énekelte: „Ha mi ülnénk, míg a Küldött dolgozik, az tévelygő tett volna részünkről.\"",
      "Egyikük ezt a verset énekelte:\n\n*„Ha mi ülnénk, míg a Küldött dolgozik,*\n\n*az tévelygő tett volna részünkről!\"*"),
    E("ENG", "5.2361b", "and they would cheer themselves up by singing: \"O Allah (ﷻ), there is no life except the life of the Hereafter, So forgive the Anṣār and the muhajirīn!\" The Companions",
      "and they would cheer themselves up by singing:\n\n*\"O Allah (ﷻ), there is no life except the life of the Hereafter,*\n\n*So forgive the Anṣār and the muhajirīn!\"*\n\nThe Companions"),
    E("ENG", "5.2361c", "One of them sang this couplet: \"If we sat down while the Messenger was working, that would be a misguided deed on our part.\"",
      "One of them sang this verse:\n\n*\"If we sat down while the Messenger was working,*\n\n*that would be a misguided deed on our part!\"*"),
    E("HUN", "5.2365a", "nevelte az emberek közül való angyalokat, a hatalmas személyiségek nevelőit és a Túlvilág uralkodóit.", "nevelte az emberek közül való angyalokat, a zsarnokok megfegyelmezőit és a Túlvilág királyait."),
    E("ENG", "5.2365a", "nurtured the angels from among people, the educators of mighty personalities and the monarchs of the Hereafter.", "nurtured the angels from among people, the disciplinarians of tyrants and the kings of the Hereafter."),
    E("HUN", "5.2365b", "A mecset helye az iszlám társadalomban egyedülálló. Intézmény. A szellemi", "A mecset helye az iszlám társadalomban egyedülálló. A szellemi"),
    E("ENG", "5.2365b", "The status of the mosque in Islāmic society is unique. It is an institution. It is the source", "The status of the mosque in Islāmic society is unique. It is the source"),
    E("HUN", "5.2377", "A Próféta (ﷺ) ezt a testvériséget végrehajtandó szerződéssé tette — nem puszta szóvá, amely vérhez és vagyonhoz kötődik, és nem is a nyelv által elmormolt, hatástalan üdvözléssé.",
      "A Próféta (ﷺ) ezt a testvériséget kötelező erejű szerződéssé tette, nem üres szóvá; vérhez és vagyonhoz kötött tetté, nem a nyelvek által elfecsegett, nyomtalan üdvözléssé."),
    E("ENG", "5.2377", "The Prophet (ﷺ) made this brotherhood into a contract to be executed, not a mere word and deed linked to blood and wealth, nor a mere greeting muttered by the tongue and having no effect.",
      "The Prophet (ﷺ) made this brotherhood into a binding contract, not an empty word; a deed bound up with blood and wealth, not a greeting babbled by tongues and leaving no effect."),
    E("HUN", "5.2415", "Amikor tehát kinyilatkoztatott az āyah („És mindenkinek rendeltünk…\"), ez hatályát vesztette; majd kinyilatkoztatott az āyah többi része: „és akikkel jobb kezetek szövetséget kötött, adjátok meg nekik részüket.\"",
      "Amikor tehát kinyilatkoztatott az āyah („És mindenkinek rendeltünk…\"), ez hatályát vesztette. Majd [Ibn 'Abbās] így folytatta: „és akikkel jobb kezetek szövetséget kötött, adjátok meg nekik részüket\" — vagyis támogatást, segítséget és jó tanácsot; az örökösödés megszűnt, de végrendeletileg lehet hagyni nekik."),
    E("ENG", "5.2415", "So when the āyah (And unto each We have...) was revealed, this was abrogated then the rest of the āyah was revealed: \"and as for those with whom your right hands have made a covenant, give them their due.\"",
      "So when the āyah (And unto each We have...) was revealed, this was abrogated. Then [Ibn 'Abbās] went on: \"and as for those with whom your right hands have made a covenant, give them their due\" — that is, support, aid and sincere counsel; inheritance was abolished, but a bequest may be made to them."),
    E("HUN", "5.2439", "Banū Jasham, Banū Aus stb.", "Banū Jasham, Banū al-Aws stb."),
    E("ENG", "5.2439", "Banū Jasham, Banū Aus, etc,", "Banū Jasham, Banū al-Aws, etc.,"),
    E("HUN", "5.2551", "Az-Zuhri mondja:", "Al-Zuhrī mondja:"),
    E("ENG", "5.2551", "Az Zuhri says:", "Al-Zuhrī says:"),
    E("HUN", "5.2579", "a Próféta (ﷺ) szavával: „Tanú — amíg velük vagyok.\"", "a Próféta (ﷺ) szavával: „(…tanú, amíg közöttük voltam…) (Korán 5: 117)\"."),
    E("ENG", "5.2579", "said by the Prophet (ﷺ): \"A witness as long as I am with them.\"", "said by the Prophet (ﷺ): \"(…a witness over them while I dwelt amongst them…) (Qur'ān 5: 117)\"."),
    E("HUN", "5.2609", "az āyában: (Egyedül Téged imádunk, és egyedül Tőled kérünk segítséget), és amelyet (ﷻ) a teremtés céljává tett az āyában: (Nem teremtettem a dzsinneket és az embereket másért, mint hogy Engem imádjanak) —",
      "az āyában: (Egyedül Téged imádunk, és egyedül Tőled kérünk segítséget) (Korán 1: 5), és amelyet (ﷻ) a teremtés céljává tett az āyában: (Nem teremtettem a dzsinneket és az embereket másért, mint hogy Engem imádjanak) (Korán 51: 56) —"),
    E("ENG", "5.2609", "in the āyah: (You alone we worship and from you alone we seek help,) and which He (ﷻ) made the purpose of creation in the āyah: (I have not created jinn or men except to worship me,) mean",
      "in the āyah: (You alone we worship and from you alone we seek help) (Qur'ān 1: 5), and which He (ﷻ) made the purpose of creation in the āyah: (I have not created jinn or men except to worship me) (Qur'ān 51: 56), mean"),
    E("HUN", "5.2619", "Nézd Ḥudhayfah ibn al Yamānt, amikor az Árok csatájában, egy üvöltő szelekkel teli, hideg téli éjszakán elindult kikémlelni a bálványimádókat. Később ezt mondta magáról: „Mintha a halál torkába gázoltam volna.\"",
      "Nézd Ḥudhayfah ibn al Yamānt, amikor az Árok csatájában, egy üvöltő szelekkel teli, hideg téli éjszakán elindult kikémlelni a bálványimádókat —\n\n*olyan éjszakán, amelyen a kutya csak egyszer ugat, aztán farkát orrára tekerve összekucorodik!!*\n\nKésőbb ezt mondta magáról: „Mintha meleg fürdőben jártam volna.\" A hit melege járta át a férfit, és ez vitte be a hideg éjszaka mélyébe."),
    E("ENG", "5.2619", "Look at Ḥudhayfah ibn al Yamān when he went off to spy on the idolaters in the Battle of the Trench during a cold wintry night filled with howling winds. He said later about himself: \"It was as if I were wading into the jaws of death.\"",
      "Look at Ḥudhayfah ibn al Yamān when he went off to spy on the idolaters in the Battle of the Trench during a cold wintry night filled with howling winds —\n\n*a night on which the dog barks but once, then curls up with its tail wrapped over its nose!!*\n\nHe said later about himself: \"It was as if I were walking in a warm bath.\" The warmth of faith had flooded the man, and it carried him into the depths of the cold night."),
    E("HUN", "5.2629", "és úgy menekíttetik a bálványimádás gonoszságaitól,", "és úgy menekülnek a bálványimádás gonoszságaitól,"),
    E("HUN", "5.2657", "A Prófétával (ﷺ) voltunk — béke legyen vele —, és ő kézen fogta", "A Prófétával (ﷺ) voltunk, és ő kézen fogta"),
    E("HUN", "5.2669", "ahogyan a Fáraó és családja tette magát istenné.", "ahogyan a Fáraó és a hozzá hasonló zsarnokok tették magukat istenné."),
    E("ENG", "5.2669", "as Pharaoh and his family made themselves gods.", "as Pharaoh and tyrants like him made themselves gods."),
    E("HUN", "5.2689", "Thaubān, a Próféta (ﷺ)", "Thawbān, a Próféta (ﷺ)"),
    E("ENG", "5.2689", "Thaubān, the close associate", "Thawbān, the close associate"),
    E("HUN", "5.2701", "Allah kegye tehát, hogy a nagy embereket olyanokkal vette körül, akik szeretik őket — a nagyság szépségét.", "Allah kegye tehát, hogy a nagyokhoz csatolja azokat, akik szeretik bennük a nagyság szépségét."),
    E("ENG", "5.2701", "It is a bounty of Allāh, therefore, that He has caused the great people to be surrounded by those who love them, the beauty of greatness.", "It is a bounty of Allāh, therefore, that He joins to the great those who love in them the beauty of greatness."),
    E("HUN", "5.2715", "Társai élén járt, és elsőként köszöntött", "Társait maga előtt engedte, és elsőként köszöntött"),
    E("ENG", "5.2715", "He led his Companions and he first greeted", "He let his Companions walk ahead of him and he was the first to greet"),
    E("HUN", "5.2721a", "Soha semmit nem bírált, és sosem bírált vagy dicsért ízlelő embert azért, amit evett.", "Soha semmit nem bírált, és sosem bírálta vagy dicsérte az ételt, amelyet megízlelt."),
    E("ENG", "5.2721a", "He never criticized anything, and he never criticized nor praised a man of taste for what he ate.", "He never criticized anything, and he never criticized nor praised any food he tasted."),
    E("HUN", "5.2721b", "Nevetése kevesebb volt a mosolynál, és jégverés vagy hasonló idején elcsendesedett.", "Nevetése többnyire mosoly volt, és ilyenkor jégszemekhez hasonló fogai villantak ki."),
    E("ENG", "5.2721b", "His laugh was less than a smile and he would become listless in a hailstorm or the like.", "His laughter was mostly a smile, revealing teeth like hailstones."),
    E("HUN", "5.2733", "— és nem várt elismerést, csak attól, aki képes rá adni.\"²¹", "— és dicséretet csak attól fogadott el, aki jótettet viszonzott vele.\"²¹"),
    E("ENG", "5.2733", "and he would not seek appreciation except from someone capable.\"²¹", "and he would accept praise only from one who was repaying a favour.\"²¹"),
    E("HUN", "5.2737", "ellenük fel kellett készülni a harcra, míg a föld meg nem tisztul hitetlenségüktől és ellenségességüktől.", "ellenük fel kellett készülni a harcra, míg a föld meg nem tisztul hitetlenségüktől és ellenségességüktől:\n\n(Bizony, akik hitetlenek és igazságtalanok, azoknak Allah nem fog megbocsátani, és semmilyen útra nem vezeti őket, csak a Pokol útjára, amelyben örökké, mindörökké maradnak. És ez Allahnak könnyű.) (Korán 4: 168–169)"),
    E("ENG", "5.2737", "it was essential to equip oneself to fight them until the earth was purified of their disbelief and enmity.", "it was essential to equip oneself to fight them until the earth was purified of their disbelief and enmity:\n\n(Lo! those who disbelieve and deal in wrong, Allāh will never forgive them, neither will He guide them unto a road, Except the road of hell, wherein they will abide for ever. And that is ever easy for Allāh.) (Qur'ān 4: 168-169)"),
    # footnotes
    E("HUN", "5.f4", "Ibn Jarīr hiteles lánccal az első khutba egy másik változatát beszélte el, amely ettől teljesen különbözik. Ez a hadísz némely bonyodalmak miatt is gyenge.",
      "Ibn Jarīr hiteles lánccal Sa'd ibn 'Abd al-Raḥmān al-Jumaḥītól beszélte el, hogy hozzá eljutott a Próféta (ﷺ) első medinai péntekén mondott khuṭba szövege — ez azonban teljesen különbözik Abū Salamah változatától. Ez az al-Jumaḥī a Tābi'ūn követőitől (pl. Hishām ibn 'Urwától) hagyományoz, így ez a változat is gyenge, mert mu'ḍal."),
    E("ENG", "5.f4", "Ibn Jarīr narrated with a sound chain another version of the first khutba which is totally different from this. This Ḥadīth is also weak owing to some complications.",
      "Ibn Jarīr narrated with a sound chain from Sa'd ibn 'Abd al-Raḥmān al-Jumaḥī that the text of the Prophet's (ﷺ) sermon at his first Friday prayer in Madīnah had reached him — and it is totally different from Abū Salamah's version. This al-Jumaḥī narrates from the Followers of the Tābi'ūn (such as Hishām ibn 'Urwah), so this version too is weak, because it is mu'ḍal."),
    E("HUN", "5.f6a", "Ḥākim ibn Jubayr útján, Jami'i bn 'Umayrtól, 'Umartól.", "Ḥakīm ibn Jubayr útján, Jumay' ibn 'Umayrtól, Ibn 'Umartól."),
    E("ENG", "5.f6a", "Ḥākim ibn Jubayr from Jami'i bn 'Umayr from 'Umar.", "Ḥakīm ibn Jubayr from Jumay' ibn 'Umayr from Ibn 'Umar."),
    E("HUN", "5.f6b", "Al Tirmidhī azt mondja: „Ez jó és erős hadísz.\"", "Al Tirmidhī azt mondja: „Ez jó, ritka (ḥasan gharīb) hadísz.\""),
    E("ENG", "5.f6b", "Al Tirmidhī says: \"This is a good and strong Ḥadīth.\"", "Al Tirmidhī says: \"This is a ḥasan gharīb Ḥadīth.\""),
    E("HUN", "5.f6c", "és azt mondta, hogy Ḥākim ibn Jubayr gyenge volt, és sī'a-gyanús. Azt mondom: ő is, Al Tirmidhī is elvétette a hadísz valódi gyengeségét, ami az, hogy Jam'ī bin 'Amir rāfiḍa volt (szélsőséges csoporthoz tartozó), aki koholt. Azt is mondta: „'Amir a legelvetemültebb hazugok egyike volt.\"",
      "és azt mondta, hogy Ḥakīm ibn Jubayr gyenge volt, és síita hajlammal vádolták. Azt mondom: ő is, Al Tirmidhī is elvétette a hadísz valódi gyengeségét, amely ez a Jumay' ibn 'Umayr. Al-Dhahabī azt mondja az *Al-Mīzān*ban: „Ibn Ḥibbān azt mondta: rāfiḍī (szélsőséges síita), aki hadíszokat koholt; és azt mondta, hogy 'Umayr [így] a leghazugabb emberek egyike volt.\""),
    E("ENG", "5.f6c", "and said that Ḥākim ibn Jubayr was weak and suspected of being a Shi'ah. I say that both he and Al Tirmidhī missed the real weakness of the Ḥadīth, which is that Jam'ī bin 'Amir was a rāfiḍa (belonging to an extremist group) who fabricated. He also said: 'Amir was one of the worst liars.\"",
      "and said that Ḥakīm ibn Jubayr was weak and accused of Shī'ite leanings. I say that both he and Al Tirmidhī missed the real weakness of the Ḥadīth, which is this Jumay' ibn 'Umayr. Al-Dhahabī says in *Al-Mīzān*: \"Ibn Ḥibbān said: a Rāfiḍī who fabricated ḥadīth; and he said that 'Umayr [sic] was one of the most mendacious of people.\""),
    E("HUN", "5.f6d", "A kérdéses hadíszt Sālim ibn Abū Ḥanīfah al Kahili is közölte, és Al-Kāhilit Ibn Abi Shaybah meg Mūsā ibn Hārūn hazugnak nyilvánította.",
      "A kérdéses hadíszt Sālim ibn Abī Ḥanīfah al-Kāhilī is közölte — Al-Ḥākim Ḥakīm ibn Jubayr megerősítéseként hozta fel —, mire Al-Dhahabī a *Talkhīṣ*ben megjegyezte: „Jumay'-t [hazugsággal] vádolták, al-Kāhilī pedig elvetemült.\" Azt mondom: Al-Kāhilīt Ibn Abī Shaybah és Mūsā ibn Hārūn hazugnak nyilvánította."),
    E("ENG", "5.f6d", "The Ḥadīth in question is also reported by Sālim ibn Abū Ḥanīfah al Kahili, and Al-Kāhili has been declared a liar by Ibn Abi Shaybah and Mūsā ibn Hārūn.",
      "The Ḥadīth in question is also reported by Sālim ibn Abī Ḥanīfah al-Kāhilī — Al-Ḥākim cited it as a corroboration of Ḥakīm ibn Jubayr — and Al-Dhahabī remarked in the *Talkhīṣ*: \"Jumay' is accused [of lying], and al-Kāhilī is ruined.\" I say: Al-Kāhilī has been declared a liar by Ibn Abī Shaybah and Mūsā ibn Hārūn."),
    E("HUN", "5.f8", "Ṣaḥīḥ Sunan Abi Dāw'ūd című könyvemben.", "Ṣaḥīḥ Sunan Abī Dāwūd című könyvemben."),
    E("ENG", "5.f8", "Ṣaḥīḥ Sunan Abi Dāw'ūd.", "Ṣaḥīḥ Sunan Abī Dāwūd."),
    E("HUN", "5.f18a", "Azon túl, hogy láncában zavar van, Al Kalbī hírhedt hazug.", "Azon túl, hogy mu'ḍal, Al Kalbī hírhedt hazug."),
    E("ENG", "5.f18a", "Apart from the fact that there is a disturbance in its chain, Al Kalbī is a noted liar.", "Apart from its being mu'ḍal, Al Kalbī is a noted liar."),
    E("HUN", "5.f18b", "Abū Na'im az Al-Ḥulyában", "Abū Nu'aym az Al-Ḥilyában"),
    E("ENG", "5.f18b", "by Abū Na'im in Al-Ḥulyah", "by Abū Nu'aym in Al-Ḥilyah"),
    E("HUN", "5.f21a", "„Egy férfi közölte velem a Banū Tamīmból, Abū Hālah gyermekei közül — Abū 'Abdullāh Ibn Abi Hālának hívják —, és ő Hasantól, 'Alī (رضي الله عنه) fiától hallotta.\"",
      "„Egy férfi közölte velem a Banū Tamīmból, Abū Hālahnak — Khadījah férjének — utódai közül, akit Abū 'Abdullāhnak hívnak, Abū Hālah egyik fiától, az pedig Al-Ḥasan ibn 'Alītól (رضي الله عنه).\""),
    E("ENG", "5.f21a", "\"It was reported to me by a man from the Banū Tamīm, of the children of Abū Hālah, and he is called Abū 'Abdullāh Ibn Abi Hālah, and he heard it from Hasan, son of 'Alī (رضي الله عنه).\"",
      "\"It was reported to me by a man from the Banū Tamīm, of the descendants of Abū Hālah, the husband of Khadījah, who is called Abū 'Abdullāh, from a son of Abū Hālah, from Al-Ḥasan ibn 'Alī (رضي الله عنه).\""),
    E("HUN", "5.f21b", "míg Hind ibn Abi Hāláról nem állapíttatott meg, hiteles-e vagy sem.", "Abū Hālah fiát, Hind ibn Abī Hālahot pedig sem el nem ítélték, sem megbízhatónak nem nyilvánították (mastūr)."),
    E("ENG", "5.f21b", "while Hind ibn Abi Hālah has not been assessed as authentic or not.", "while the son of Abū Hālah, Hind ibn Abī Hālah, is mastūr (neither criticized nor declared reliable)."),
]
