# Ch6 parts 1–2 (harc engedélyezése → Badr → foglyok előtt) — see opus55-findings.md "Ch6 — part 1/2"
from apply import E

EDITS = [
    E("HUN", "6.2849", "Faqīm Al-Lahmi mondta:", "Fuqaym al-Lakhmī mondta:"),
    E("ENG", "6.2849", "Faqīm Al-Lahmi said:", "Fuqaym al-Lakhmī said:"),
    E("HUN", "6.2869", "„Bizony, a Mindenható Isten három embert juttat", "„Bizony, Allah (ﷻ) három embert juttat"),
    E("ENG", "6.2869", "\"Indeed God Almighty brings three people into paradise", "\"Indeed Allāh (ﷻ) brings three people into Paradise"),
    E("HUN", "6.S'ad", "S'ad ibn", "Sa'd ibn", count=3),
    E("ENG", "6.S'ad", "S'ad ibn", "Sa'd ibn", count=3),
    E("HUN", "6.2896", "Wadanig vonult, ahol a Quraishsal és a Banū Damrával remélt találkozni; a Quraisht ugyan nem találta, a Banū Damrával azonban szövetséget kötött.", "Waddānig vonult, ahol a Quraishsal és a Banū Ḍamrával remélt találkozni; a Quraisht ugyan nem találta, a Banū Ḍamrával azonban szövetséget kötött."),
    E("ENG", "6.2896", "He travelled until he reached Wadan, where he hoped to encounter the Quraish and the Banū Damrah, although he did not meet the Quraish, and he concluded an alliance with the Banū Damrah.", "He travelled until he reached Waddān, where he hoped to encounter the Quraish and the Banū Ḍamrah, although he did not meet the Quraish, and he concluded an alliance with the Banū Ḍamrah."),
    E("HUN", "6.2897", "Ugyanezen év Rabi'-1 havában", "Ugyanezen év Rabī' al-Awwal havában"),
    E("ENG", "6.2897", "In Rabi'-1 of the same year,", "In Rabī' al-Awwal of the same year,"),
    E("HUN", "6.2898", "6. Jumādában Al-'Ashīrába ment, ahol egy hónapot töltött, és békeszerződést kötött a Banū Madlajjal.", "6. Jumādában a Yanbu' völgyében fekvő al-'Ushayrahba ment, ahol egy hónapot töltött, és békeszerződést kötött a Banū Mudlijjal."),
    E("ENG", "6.2898", "6. In Jumāda he went to Al-'Ashīrah where he spent one month and concluded a peace treaty with the Banū Madlaj.", "6. In Jumāda he went to al-'Ushayrah in the valley of Yanbu', where he spent one month and concluded a peace treaty with the Banū Mudlij."),
    E("HUN", "6.2913", "amikor a mekkaiaknak adnak igazat, és az iszlámon meg eredetén siránkoznak.", "amikor a mekkaiaknak adnak igazat, és az iszlámot meg eredetét ócsárolják."),
    E("ENG", "6.2913", "in their approval of the Makkans and lamentations at Islām and its origin.", "in their approval of the Makkans and their censure of Islām and its origin."),
    E("HUN", "6.2929", "És tanácstalanság támadt afelől, mi legyen a karavánnal és a foglyokkal.", "A Próféta (ﷺ) pedig felfüggesztette a karavánnal és a két fogollyal kapcsolatos döntést."),
    E("ENG", "6.2929", "And there was indecision over what to do with the caravan and prisoners.", "And [the Prophet (ﷺ)] suspended any decision on the caravan and the two captives."),
    E("HUN", "6.2967", "Abū Lababah és 'Alī ibn Abī Ṭālib", "Abū Lubābah és 'Alī ibn Abī Ṭālib"),
    E("ENG", "6.2967", "Abū Lababah and 'Alī ibn Abī Ṭālib", "Abū Lubābah and 'Alī ibn Abī Ṭālib"),
    E("HUN", "6.2973", "Damdam ibn 'Amr al-Ghifarit", "Ḍamḍam ibn 'Amr al-Ghifārīt"),
    E("ENG", "6.2973", "sent Damdam ibn 'Amr al-Ghifari", "sent Ḍamḍam ibn 'Amr al-Ghifārī"),
    E("HUN", "6.2975", "Damdamnak sikerült", "Ḍamḍamnak sikerült"),
    E("ENG", "6.2975", "Damdam was able", "Ḍamḍam was able"),
    E("HUN", "6.2985", "s a lányok nem énekelnek és táncolnak nekünk.", "s az énekesnők nem muzsikálnak nekünk."),
    E("ENG", "6.2985", "and have the girls sing and dance for us.", "and have the singing-girls play for us."),
    E("HUN", "6.3013", "Ta'imah ibn 'Adi,", "Ṭu'aymah ibn 'Adī,"),
    E("ENG", "6.3013", "Ta'imah ibn 'Adi,", "Ṭu'aymah ibn 'Adī,"),
    E("HUN", "6.3027a", "Sa'd ibn M'ādh így felelt", "Sa'd ibn Mu'ādh így felelt"),
    E("ENG", "6.3027a", "Sa'd Ibn M'ādh replied", "Sa'd ibn Mu'ādh replied"),
    E("HUN", "6.3027b", "Arra (ﷻ), aki az igazsággal küldött el téged:", "Arra, Aki az igazsággal küldött el téged:"),
    E("HUN", "6.3055", "Ő azonban tovább ugrált a medence felé, Ḥamzah pedig követte.", "Ő azonban a medence felé mászott, hogy belevesse magát, Ḥamzah pedig harcolva követte, míg meg nem ölte benne."),
    E("ENG", "6.3055", "But he continued to hop toward the pool, followed by Ḥamzah.", "But he crawled toward the pool, seeking to plunge into it, and Ḥamzah followed him, fighting him until he killed him in it."),
    E("HUN", "6.3059", "'Ubaydah ibn-ul Ḥārith;", "'Ubaydah ibn al-Ḥārith;"),
    E("ENG", "6.3059", "'Ubaydah ibn-ul Ḥārith;", "'Ubaydah ibn al-Ḥārith;"),
    E("HUN", "6.3071", "a hamisság seregét pedig az a téveszme szállta meg, hogy legyőzheti az igazságot.", "a hamisság seregét pedig az a téveszme szállta meg, hogy megbirkózhat a végzettel."),
    E("ENG", "6.3071", "and the army of falsehood possessed by the delusion that they could vanquish truth.", "and the army of falsehood possessed by the delusion that they could wrestle with destiny."),
    E("HUN", "6.3077", "A túlvilág szemlélése az a kincs, amelyet a Próféta (ﷺ) kínált. De vajon van-e nyugalom a hit fenntartói és az igazság megváltói számára máshol, mint odaát?", "A túlvilág szemlélése a próféták portékája. És vajon van-e nyugalom a hit fenntartói és az igazságért életüket áldozók számára máshol, mint odaát?"),
    E("ENG", "6.3077", "Contemplation of the Hereafter is the commodity which the Prophet (ﷺ) offered. However, is there any rest for the upholders of faith and the redeemers of truth except over there?", "Contemplation of the Hereafter is the merchandise of the prophets. And is there any rest for the upholders of faith and those who sacrifice themselves for the truth except over there?"),
    E("HUN", "6.3081", "'Umayr ibn-ul Hamām Al-Anṣārī", "'Umayr ibn al-Ḥumām al-Anṣārī"),
    E("ENG", "6.3081", "'Umayr ibn-ul Hamām Al-Anṣārī", "'Umayr ibn al-Ḥumām al-Anṣārī"),
    E("HUN", "6.3085", "amelyet szarujában tartott,", "amelyet tegezében tartott,"),
    E("ENG", "6.3085", "which he had in his horn", "which he had in his quiver"),
    E("HUN", "6.3095", "Harcolt, míg el nem esett.¹⁹", "Harcolt, míg el nem esett."),
    E("ENG", "6.3095", "He fought until he was killed.¹⁹", "He fought until he was killed."),
    E("HUN", "6.3097", "felkiáltott: „Torzuljanak el arcaik!\"", "felkiáltott: „Torzuljanak el arcaik!\"¹⁹"),
    E("ENG", "6.3097", "cried out: \"May their faces be disfigured.\"", "cried out: \"May their faces be disfigured!\"¹⁹"),
    E("HUN", "6.3103", "szemét még mindig a téveszme köteléke fedte:", "szemét még mindig a téveszme fátyla fedte:"),
    E("HUN", "6.3105", "*„Miféle bosszút állhat rajtam a vad háború?*\n\n*Két évet is meghalad koromnak beszéde.*\n\n*Mert ilyennek szült engem anyám.\"*", "*„Mit bosszulhat rajtam a dühödt háború?*\n\n*Teljes erőm javában vagyok, bár ifjú koromban;*\n\n*ilyen napra szült engem anyám!\"*"),
    E("ENG", "6.3105", "*\"What revenge can a wild war take of me?*\n\n*Exceeding two years is the talk of my age.*\n\n*For such did my mother give birth to me.\"*", "*\"What can the raging war avenge on me?*\n\n*I am a camel in full prime, though young in years;*\n\n*for the like of this did my mother bear me!\"*"),
    E("HUN", "6.3111", "Sűrű erdő közepén állt. Ám ez az erdő", "Mintegy sűrű erdő közepén állt közöttük. Ám ez az erdő"),
    E("ENG", "6.3111", "He was in the midst of a thick forest. Nevertheless, this forest", "He was among them as if in the midst of a thick forest. Nevertheless, this forest"),
    E("HUN", "6.3133a", "„És mivel alázott meg? Van-e erősebb ember annál, akit saját népe öl meg?\"", "„És mivel alázott meg? Vagyok-e több, mint egy ember, akit a saját népe ölt meg?\""),
    E("ENG", "6.3133a", "\"And how did He humiliate me? Is there any man stronger than the one who is killed by his own people?", "\"And how did He humiliate me? Am I anything more than a man killed by his own people?\""),
    E("HUN", "6.3133b", "„Nem te vagy-e a mekkai kis pásztorfiú?\"", "„Nem te vagy-e a mi kis mekkai pásztorfiúnk?\""),
    E("ENG", "6.3133b", "\"Aren't you the little shepherd boy in Makkah?\"", "\"Aren't you our little shepherd boy in Makkah?\""),
    E("HUN", "6.3139", "eltévedt nyílvessző ölte meg, miközben őrségben állt.", "eltévedt nyílvessző ölte meg, miközben a nézelődők között volt."),
    E("ENG", "6.3139", "by a stray arrow while on guard.", "by a stray arrow while among the onlookers."),
    E("HUN", "6.3141", "(vagyis jajveszékel). És még nem fosztatott meg a reménytől.", "(vagyis jajveszékel). A jajveszékelés ugyanis akkor még nem volt tiltott!!"),
    E("ENG", "6.3141", "(That is, wailing). And she was not yet deprived.", "(That is, wailing). For wailing had not yet been forbidden!!"),
    E("HUN", "6.3143", "„Jaj neked! Hát megfosztattál-e fiadtól? Azok csodálatos kertek, és fiad", "„Jaj neked! Elment az eszed? Nyolc kert van ott, és fiad"),
    E("ENG", "6.3143", "\"Woe you! Are you bereft of your son? Those are wonderful gardens and your son", "\"Woe to you! Have you lost your mind? There are eight gardens, and your son"),
    E("HUN", "6.3145", "Ha ez volt a jutalma az eltévedt nyílvesszőtől talált őröknek,", "Ha ez volt a jutalma a nézelődőnek, akit eltévedt nyílvessző talált el,"),
    E("ENG", "6.3145", "If this was the reward for the guards who were hit by stray arrows,", "If this was the reward for an onlooker who was hit by a stray arrow,"),
    E("HUN", "6.3149a", "fia pedig Abū Jahl oldalán harcolt ellene.", "fia, 'Abd al-Raḥmān pedig Abū Jahl oldalán harcolt ellene."),
    E("ENG", "6.3149a", "and his son with Abū Jahl was fighting against him.", "and his son 'Abd al-Raḥmān was with Abū Jahl, fighting against him."),
    E("HUN", "6.3149b", "míg fia, Abū Hudhayfah a Próféta (ﷺ)", "míg fia, Abū Ḥudhayfah a Próféta (ﷺ)"),
    E("ENG", "6.3149b", "while his son Abū Hudhayfah was one", "while his son Abū Ḥudhayfah was one"),
    E("HUN", "6.3149c", "hogy a (holttesteknek ásott) gödörbe vessék, a Próféta (ﷺ) Abū Hudhayfára nézett,", "hogy a kútba (qalīb) vessék, a Próféta (ﷺ) Abū Ḥudhayfára nézett,"),
    E("ENG", "6.3149c", "to be thrown into the pit (dug for the bodies), the Prophet (ﷺ) looked at Abū Hudhayfah", "to be thrown into the well (qalīb), the Prophet (ﷺ) looked at Abū Ḥudhayfah"),
    E("HUN", "6.3151", "„Abū Hudhayfah, talán bánt,", "„Abū Ḥudhayfah, talán bánt,"),
    E("ENG", "6.3151", "\"Abū Hudhayfah, are you upset,", "\"Abū Ḥudhayfah, are you upset,"),
    E("HUN", "6.3155", "holttesteit vessék a gödörbe, és úgy beszélik, láttukra így szólt: „Milyen hitvány rokonai voltatok Prófétátoknak, egy próféta rokonaiként!", "holttesteit vessék a kútba, és úgy beszélik, láttukra így szólt: „Milyen rossz rokonság voltatok a prófétátok számára!"),
    E("ENG", "6.3155", "to be thrown into the pit, and it is narrated that upon seeing them he said: \"What a bad lot you were to your Prophet, as relatives of a prophet.", "to be thrown into the well, and it is narrated that upon seeing them he said: \"What a bad kinsfolk you were to your Prophet!"),
    E("HUN", "6.3157", "és amikor a gödörhöz ért,", "és amikor a kúthoz ért,"),
    E("ENG", "6.3157", "and when he reached the pit,", "and when he reached the well,"),
    E("HUN", "6.3159", "„Ó, gödör népe!", "„Ó, kút népe!"),
    E("ENG", "6.3159", "\"O people of the pit!", "\"O people of the well!"),
    E("HUN", "6.f4", "Mi'din ibn Abī Ṭalḥa", "Ma'dān ibn Abī Ṭalḥah"),
    E("ENG", "6.f4", "Mi'din ibn Abī Ṭalḥa", "Ma'dān ibn Abī Ṭalḥah"),
    E("HUN", "6.f5", "Akhrij Al Iḥyā című könyvében.", "*Takhrīj al-Iḥyā'* című könyvében."),
    E("ENG", "6.f5", "in his book Akhrij Al Iḥyā.", "in his book *Takhrīj al-Iḥyā'*."),
]
