# Ch6 part 3 (Számvetés → Badr utóhatása → Zsidók → Csetepaték → Uḥud eleje) — see opus55-findings.md "Ch6 part 3"
from apply import E

EDITS = [
    E("HUN", "6.3241", "Bocsássatok meg és legyetek elnézőek [irántuk], míg Allah parancsot nem ad.) (Korán 2: 109)", "Bocsássatok meg és legyetek elnézőek [irántuk], míg Allah parancsot nem ad. Bizony, Allah mindenre képes.) (Korán 2: 109)"),
    E("ENG", "6.3241", "Forgive and be indulgent [towards them] until Allāh gives a command.) (Qur'ān 2: 109)", "Forgive and be indulgent [towards them] until Allāh gives a command. Lo! Allāh is Able to do all things.) (Qur'ān 2: 109)"),
    E("HUN", "6.3245", "esküdjünk hát hűséget a Prófétának (ﷺ), és fogadjuk el az iszlámot.\"", "esküdjünk hát hűséget a Prófétának (ﷺ), és fogadjuk el az iszlámot.\" Így is tettek, és felvették az iszlámot."),
    E("ENG", "6.3245", "so let us swear allegiance to the Prophet (ﷺ) and accept Islām.\"", "so let us swear allegiance to the Prophet (ﷺ) and accept Islām.\" So they did, and embraced Islām."),
    E("HUN", "6.3249a", "Még Medinát is kifosztották javaiból,", "Korábban Medina jószágát is elhajtották,"),
    E("ENG", "6.3249a", "They had even robbed Madīnah of its bounties,", "They had previously driven off Madīnah's livestock,"),
    E("HUN", "6.3249b", "Elképedtek a muszlimok badri győzelmén.", "Megriadtak a muszlimok badri győzelmétől."),
    E("ENG", "6.3249b", "They were astounded at the victory of the Muslims in Badr.", "They were alarmed at the victory of the Muslims in Badr."),
    E("HUN", "6.3259", "visszafogták volna nyelvüket Allah (ﷻ) Prófétájának rágalmazásától", "visszafogták volna nyelvüket Allah (ﷻ) prófétáinak rágalmazásától"),
    E("ENG", "6.3259", "restrained their tongues from slandering the Prophet of Allāh (ﷻ),", "restrained their tongues from slandering the prophets of Allāh (ﷻ),"),
    E("HUN", "6.3265", "A második āyāt emlékeztető", "A második āyah emlékeztető"),
    E("ENG", "6.3265", "The second āyāh is a reminder", "The second āyah is a reminder"),
    E("HUN", "6.3271", "„Ó, Próféta (ﷺ), légy kegyes védenceimhez!\"", "„Ó, Mohamed (ﷺ), légy kegyes védenceimhez!\""),
    E("ENG", "6.3271", "\"O Prophet (ﷺ), be kind to my clients.\"", "\"O Muhammad (ﷺ), be kind to my clients.\""),
    E("HUN", "6.3273", "és így szólt: „Engedj el!\"", "és így szólt: „Engedj el, jaj neked!\""),
    E("ENG", "6.3273", "and he said: \"Let me go!\"", "and he said: \"Let me go, woe to you!\""),
    E("HUN", "6.3275", "ők védtek meg engem mindenki fiától.", "ők védtek meg engem mindenkitől, vöröstől és feketétől."),
    E("HUN", "6.3303", "még gúnyverseket is költött egyes muszlim asszonyokról. Ez túllépte a tűrés határait, ezért a muszlimok kiontották vérét.", "még szerelmes verseket is költött egyes muszlim asszonyokról. Ez túllépte a tűrés határait, ezért a muszlimok vérét szabadnak nyilvánították."),
    E("ENG", "6.3303", "he even composed odes about some of the Muslim women. This was beyond the limits of tolerance, so the Muslims spilled his blood.", "he even composed love odes about some of the Muslim women. This was beyond the limits of tolerance, so the Muslims declared his blood forfeit."),
    E("HUN", "6.nailah", "Na'ilah", "Nā'ilah", count=4),
    E("ENG", "6.nailah", "Na'ilah", "Nā'ilah", count=4),
    E("HUN", "6.3345", "sawīqból (cukorból és datolyából készült pépből) álltak", "sawīqból (pörkölt árpa- vagy búzadarából) álltak"),
    E("ENG", "6.3345", "Sawīq (a mash made of sugar and dates)", "Sawīq (parched barley or wheat meal)"),
    E("HUN", "6.3351a", "Bemutatta neki Furat ibn Huyyant", "Bemutatta neki Furāt ibn Ḥayyānt"),
    E("ENG", "6.3351a", "He introduced him to Furat ibn Huyyan", "He introduced him to Furāt ibn Ḥayyān"),
    E("HUN", "6.3351b", "csak Furat ibn Hayyn került", "csak Furāt ibn Ḥayyān került"),
    E("ENG", "6.3351b", "only Furat ibn Hayyn fell", "only Furāt ibn Ḥayyān fell"),
    E("HUN", "6.naim", "Na'im ibn Mas'ūd", "Nu'aym ibn Mas'ūd", count=2),
    E("ENG", "6.naim", "Na'im ibn Mas'ūd", "Nu'aym ibn Mas'ūd", count=2),
    E("HUN", "6.safwan", "Safwān ibn Umayyah", "Ṣafwān ibn Umayyah", count=4),
    E("ENG", "6.safwan", "Safwān ibn Umayyah", "Ṣafwān ibn Umayyah", count=4),
    E("HUN", "6.3357", "Elhunyt Khanīs ibn Ḥudhāfah al Sahmi,", "Elhunyt Khunays ibn Ḥudhāfah al-Sahmī,"),
    E("ENG", "6.3357", "Khanīs ibn Ḥudhāfah al Sahmi,", "Khunays ibn Ḥudhāfah al-Sahmī,"),
    E("HUN", "6.3373a", "A qibla Jeruzsálemből a Ka'bára változott az ez évben történtek miatt, és ez a változás", "Ez év legjelentősebb eseményei közé tartozott a qibla áthelyezése Jeruzsálemből a megtisztított Ka'bára, és ez a változás"),
    E("ENG", "6.3373a", "The qibla was changed from Jerusalem to the Ka'bah on account of what took place during this year, and this change", "Among the most momentous events of this year was the change of the qibla from Jerusalem to the purified Ka'bah, and this change"),
    E("HUN", "6.3373b", "Korábban azt remélték, hogy a Próféta (ﷺ) őket követi majd,", "Korábban azt remélték, hogy a Próféta (ﷺ) őket követi majd (!),"),
    E("ENG", "6.3373b", "Prior to it they were hoping that the Prophet (ﷺ) would follow them,", "Prior to it they were hoping that the Prophet (ﷺ) would follow them (!),"),
    E("HUN", "6.3377", "(Nem az az igazságosság, hogy kelet vagy nyugat felé fordítjátok arcotokat, hanem az az igaz, aki hisz Allahban és az Utolsó Napban…\") (Korán 2: 177)\n\n(Allahé a Kelet és a Nyugat, és bármerre fordultok, ott van Allah Orcája.) (Korán 2: 115)",
      "(Allahé a Kelet és a Nyugat, és bármerre fordultok, ott van Allah Orcája.) (Korán 2: 115)\n\n(Nem az az igazságosság, hogy kelet vagy nyugat felé fordítjátok arcotokat, hanem az az igaz, aki hisz Allahban és az Utolsó Napban…) (Korán 2: 177)"),
    E("ENG", "6.3377", "(It is no righteousness that you turn your faces to the East and the West, but righteousness is he who believes in Allāh and the Last Day..\") (Qur'ān 2: 177)\n\n(To Allāh belong the East and the West, and whichever way you turn, there is Allāh's Countenance.) (Qur'ān 2: 115)",
      "(To Allāh belong the East and the West, and whichever way you turn, there is Allāh's Countenance.) (Qur'ān 2: 115)\n\n(It is no righteousness that you turn your faces to the East and the West, but righteousness is he who believes in Allāh and the Last Day…) (Qur'ān 2: 177)"),
    E("HUN", "6.3381", "meghatározott qibla felé irányít (ﷻ),", "meghatározott qibla felé irányítja,"),
    E("HUN", "6.3391", "A Próféta (ﷺ) azonban nem vette zokon a véleménykülönbséget, és így szólt:", "A Próféta (ﷺ) azonban helytelennek tartotta, hogy a különböző vélemények között ingadozzanak, és így szólt:"),
    E("ENG", "6.3391", "The Prophet (ﷺ), however, had taken no offence at the difference of opinion and said:", "The Prophet (ﷺ), however, found it objectionable to waver between differing opinions and said:"),
    E("HUN", "6.3409", "Ő maga páncélinget viselt,³⁸", "Ő maga két páncélinget viselt egymás fölött,³⁸"),
    E("ENG", "6.3409", "He himself was clad in a coat of mail,³⁸", "He himself wore two coats of mail, one over the other,³⁸"),
    E("HUN", "6.3415", "aki a csatában öntelt arckifejezést szokott ölteni.", "aki a csatában büszkén szokott lépkedni."),
    E("ENG", "6.3415", "who used to put on a conceited air in battle.", "who used to strut proudly in battle."),
    E("HUN", "6.3417", "e szavakkal indult ki: „Én vagyok az, aki fogadalmat tett barátomnak, míg a síkságon voltunk a datolyapálmák mellett, hogy soha többé nem maradok a hátvédben, hanem Allah (ﷻ) és Prófétája (ﷺ) kardjával sújtok le.\"",
      "e szavakkal indult ki:\n\n*„Én vagyok az, akit barátom fogadalomra kötelezett,*\n\n*míg a hegy lábánál voltunk, a datolyapálmák mellett:*\n\n*hogy soha nem állok a hátsó sorokban,*\n\n*hanem Allah (ﷻ) és a Küldött (ﷺ) kardjával sújtok le!\"*\n\nA »hátsó sorokon« azt értette, hogy sohasem harcol a sorok végében, hanem mindig az élen marad."),
    E("ENG", "6.3417", "went out saying: \"It is who have pledged to my friend while we were in the plain near the date palms that I shall never remain in the rear any more, but I'll strike with the sword of Allāh (ﷻ) and His Prophet (ﷺ).\"",
      "went out saying:\n\n*\"I am the one whom my friend bound by a pledge*\n\n*while we were at the foot of the hill, beside the palms:*\n\n*never to stand in the rear ranks,*\n\n*but to strike with the sword of Allāh (ﷻ) and the Messenger (ﷺ)!\"*\n\nBy \"the rear ranks\" he meant that he would never fight at the back of the lines, but would always remain in the front."),
]
