# Ch6 part 4 (Uḥud csata) — see opus55-findings.md "Ch6 part 4"
from apply import E

EDITS = [
    E("HUN", "6.3437a", "úgy harcolt, mint egy felbőszült tigris.", "úgy harcolt, mint a felbőszült oroszlánok."),
    E("ENG", "6.3437a", "fought like an enraged tiger.", "fought like enraged lions."),
    E("HUN", "6.3437b", "Wahshi, Jubayr ibn Mut'im rabszolgája mondta:", "Waḥshī, Jubayr ibn Muṭ'im rabszolgája mondta:"),
    E("ENG", "6.3437b", "Wahshi, the slave of Jubayr ibn Mut'im said:", "Waḥshī, the slave of Jubayr ibn Muṭ'im said:"),
    E("HUN", "6.3441", "olyan volt, mint egy elszabadult teve:", "olyan volt, mint egy hamuszürke [portól szürke] teve:"),
    E("ENG", "6.3441", "he was like a runaway camel,", "he was like an ash-grey [dust-covered] camel,"),
    E("HUN", "6.3443a", "»Gyere csak ide, te nyomorult fia!«", "»Gyere csak ide, te lánykörülmetélő asszony fia!«"),
    E("ENG", "6.3443a", "\"Come to me, you son of a wretch!\"", "'Come to me, you son of the woman who circumcises girls!'"),
    E("HUN", "6.3443b", "Átfúrta a gyomrát, és a hátán jött ki.", "Az alhasába fúródott, és a két lába között jött ki."),
    E("ENG", "6.3443b", "It pierced his stomach and went through his back.", "It struck his lower belly and came out between his legs."),
    E("HUN", "6.3445a", "A muszlimok zászlaját Mus'ab ibn 'Umayr,", "A muszlimok zászlaját Muṣ'ab ibn 'Umayr,"),
    E("ENG", "6.3445a", "The banner of the Muslims was carried by Mus'ab ibn 'Umayr,", "The banner of the Muslims was carried by Muṣ'ab ibn 'Umayr,"),
    E("HUN", "6.3445b", "Csatakiáltásuk ez volt: „Amut, amut!\" (Hadd haljak meg, hadd haljak meg!)", "Csatakiáltásuk ez volt: „Amit, amit!\" (Ölj, ölj!)"),
    E("ENG", "6.3445b", "Their battle cry was \"Amut, amut\" (Let me die, let me die.)!", "Their battle cry was \"Amit, amit!\" (Kill, kill!)"),
    E("HUN", "6.3447", "aki verssorokat szavalt, a Banū 'Abd al Dart tüzelve, hogy tartsák magasan Mekka zászlaját: „Tartsatok ki mellette, Banu al Dar, tartsatok ki, ó, hátvéd oltalmazói! Sújtsatok le minden éles karddal!\" A férfiakat nógatva így szavalt: „Ha előrenyomultok, megölelünk, és szőnyegeket terítünk. De hátráljatok csak, és elválunk — nem úgy, ahogy szeretők válnak el.\"",
      "aki verssorokat szavalt, a Banū 'Abd al-Dārt tüzelve, hogy tartsák magasan Mekka zászlaját:\n\n*„Rajta, 'Abd al-Dār fiai!*\n\n*Rajta, hátvéd oltalmazói!*\n\n*Sújtsatok minden éles karddal!\"*\n\nA férfiakat nógatva így szavalt:\n\n*„Ha előrenyomultok, megölelünk,*\n\n*és szőnyegeket terítünk;*\n\n*de ha hátráltok, elválunk —*\n\n*nem úgy, ahogy szeretők válnak el!\"*"),
    E("ENG", "6.3447", "who recited couplets of poetry inciting the Banū 'Abd al Dar to keep the standard of Makkah high: \"Stay with it, Banu al Dar, stay with it, O protectors of the rear! Strike with every sharp sword.\" Urging the men on, she recited: \"If you advance we shall embrace and spread rugs. But retreat and we shall separate not as lovers separate.\"",
      "who recited verses inciting the Banū 'Abd al-Dār to keep the standard of Makkah high:\n\n*\"On, sons of 'Abd al-Dār!*\n\n*On, protectors of the rear!*\n\n*Strike with every sharp sword!\"*\n\nUrging the men on, she recited:\n\n*\"If you advance we shall embrace you,*\n\n*and spread the cushions;*\n\n*but if you retreat we shall part —*\n\n*not as lovers part!\"*"),
    E("HUN", "6.3459a", "Egy 'Amrah bint Al-Qamah nevű asszony", "Egy 'Amrah bint 'Alqamah al-Ḥārithiyyah nevű asszony"),
    E("ENG", "6.3459a", "A woman named 'Amrah bint Al-Qamah", "A woman named 'Amrah bint 'Alqamah al-Ḥārithiyyah"),
    E("HUN", "6.3459b", "Így a ṣaḥābák elölről és hátulról is szorongattatva, mintha ismét mozsár és mozsártörő közé kerültek volna.", "Így a ṣaḥābákat elölről és hátulról is bekerítették, és két malomkő közé szorultak."),
    E("ENG", "6.3459b", "Thus the Ṣaḥabah were caught in the van and the rear as if they were again caught between the mortar and pestle.", "Thus the Ṣaḥābah were surrounded in front and behind, caught between the two millstones."),
    E("ENG", "6.3459c", "were kept in confined.", "were kept confined."),
    E("HUN", "6.3467", "„Én vagyok az, aki megöli őt\" — és mellvértjén át döfte. Ettől az elesett, és bőgött, mint a bika. Egy-két nappal később meghalt.⁴¹", "„Én vagyok az, aki megöli őt, ha Allah (ﷻ) akarja\" — és mellvértje nyílásán át döfte. Ettől az elesett, és bőgött, mint a bika. Egy napot vagy annyit sem élt túl.⁴¹"),
    E("ENG", "6.3467", "\"I am the one to kill him,\" and stabbed him through his chest armour. This made him fall and moan like a bull. A day or two later he died.⁴¹", "\"I am the one to kill him, if Allāh (ﷻ) wills,\" and stabbed him through the opening of his armour. This made him fall and moan like a bull. He died within a day or part of a day.⁴¹"),
    E("HUN", "6.3471", "Anas ibn al Nasr elhaladt", "Anas ibn al-Naḍr elhaladt"),
    E("ENG", "6.3471", "Anas ibn al Nasr passed by", "Anas ibn al-Naḍr passed by"),
    E("HUN", "6.3487a", "és Sa'd ibn Abī Waqqasnak nyújtva", "és Sa'd ibn Abī Waqqāṣnak nyújtva"),
    E("ENG", "6.3487a", "handing them to Sa'd ibn Abī Waqqas,", "handing them to Sa'd ibn Abī Waqqāṣ,"),
    E("HUN", "6.3487b", "Abū Ṭalḥah pedig kidüllesztette mellét, mondván: „Apám s anyám helyett vagy nekem. Nyíl nem találhat el téged. Nyakamat adom a tiéd védelmére.\" És azt mondogatta: „Apád erős, Allah Küldötte (ﷺ), mondd hát, mire van szükséged, és parancsold, amit akarsz.\"",
      "Abū Ṭalḥah pedig elébe emelte mellkasát, mondván: „Maradj így — apám és anyám legyen váltságod! Nyíl nem találhat el téged; nyakam a te nyakad előtt!\" És azt mondogatta: „Erős vagyok, Allah Küldötte (ﷺ); küldj hát, ahová kell, és parancsold, amit akarsz!\""),
    E("ENG", "6.3487b", "Abū Ṭalḥa would inflate his chest, saying: \"You are as my father and mother. No arrow shall hit you. I shall give my neck in protection of yours. And he would say: \"My father is strong, Messenger of Allāh (ﷺ), so tell me what you need and order me to do whatever you will.\"",
      "Abū Ṭalḥah would raise his chest [to shield him], saying: \"Stay like this — may my father and mother be your ransom! No arrow shall hit you; my neck before your neck!\" And he would say: \"I am sturdy, Messenger of Allāh (ﷺ); send me wherever you need and order me to do whatever you will.\""),
    E("ENG", "6.3487c", "Abū Ṭalḥan al-Anṣārī was an expert archer,", "Abū Ṭalḥah al-Anṣārī was an expert archer,"),
    # footnotes
    E("HUN", "6.f40", "Bukhārī is elbeszélte muṭlaqként.", "Bukhārī is elbeszélte, lánc nélkül (mu'allaq)."),
    E("ENG", "6.f40", "Also Bukhārī narrated it as muṭlaq.", "Bukhārī also narrated it without a chain (mu'allaq)."),
    E("HUN", "6.f41a", "Ibn Kathīr azt mondja: „Nagyon szokatlan (gharīb), és ismeretlen személy van benne.\"", "Ibn Kathīr azt mondja: „Nagyon szokatlan (gharīb), és ebben a részében elutasítandó (munkar) tartalom van.\""),
    E("ENG", "6.f41a", "Ibn Kathīr says: \"It is very strange (gharīb) and in it is an unknown entity.\"", "Ibn Kathīr says: \"It is very strange (gharīb), and this portion of it contains objectionable (munkar) matter.\""),
    E("HUN", "6.f41b", "Sa'd ibn al Musayyib", "Sa'īd ibn al-Musayyib"),
    E("ENG", "6.f41b", "Sa'd ibn al Musayyib", "Sa'īd ibn al-Musayyib"),
    E("HUN", "6.f43", "Ugyanígy Aḥmad elbeszélése is, de egy másik változatában „erős vagyok\" áll az „apám erős\" helyett.", "Aḥmad is elbeszélte; egyik változatában ott áll Abū Ṭalḥah mondása is: „Erős vagyok…\""),
    E("ENG", "6.f43", "The same is Aḥmad's narration, but in another version he has \"I am strong\" instead of \"my father is strong.\"", "Aḥmad also narrated it; one of his versions contains Abū Ṭalḥah's words: \"I am sturdy…\""),
]
