# Ch6 part 5 (Uḥud vége → A próbatétel tanulságai) — see opus55-findings.md "Ch6 part 5"
from apply import E

EDITS = [
    E("HUN", "6.3519", "„Mondd: »Allah (ﷻ) magasztosabb és fenségesebb: a ti halottaitok a Tűzben vannak!«\"", "„Mondd: »Allah (ﷻ) magasztosabb és fenségesebb! Nem egyformák vagyunk: a mi halottaink a Paradicsomban, a ti halottaitok a Tűzben vannak!«\""),
    E("ENG", "6.3519", "\"Say: 'Allāh (ﷻ) is more exalted and sublime: your dead are in the Fire!\"", "\"Say: 'Allāh (ﷻ) is more exalted and sublime! We are not equal: our dead are in Paradise and your dead are in the Fire!'\""),
    E("HUN", "6.3529", "Abū Sufyān azt mondta: „Igazabb vagy hozzám Ibn Qamī'ánál, aki azt állította, hogy megölte Mohamedet (ﷺ).\" Majd így kiáltott:", "Ezután Abū Sufyān így kiáltott:"),
    E("ENG", "6.3529", "Abū Sufyān said: \"You are more truthful to me than Ibn Qamī'ah, who claimed that he killed Muhammad (ﷺ).\" Then he shouted:", "Then Abū Sufyān shouted:"),
    E("HUN", "6.3543a", "Ha átsiklasz a felszínen, amelyen ezek a képmutatók csúsznak-másznak,", "Ha túllépsz az alsó lejtőkön, amelyeken ezek a képmutatók csúsznak-másznak,"),
    E("ENG", "6.3543a", "If you pass over the surface upon which these hypocrites creep", "If you pass beyond the lower slopes on which these hypocrites creep"),
    E("HUN", "6.3543b", "a nemes, kimerült védekezés szakaszában,", "a nemes, félelmetes védekezés szakaszában,"),
    E("ENG", "6.3543b", "the phase of noble, exhausted defence,", "the phase of noble, tremendous defence,"),
    E("HUN", "6.3561", "Na'im ibn Mālik (رضي الله عنه)⁴⁹", "Nu'aym ibn Mālik (رضي الله عنه)⁴⁹"),
    E("ENG", "6.3561", "Na'im ibn Mālik (رضي الله عنه)⁴⁹", "Nu'aym ibn Mālik (رضي الله عنه)⁴⁹"),
    E("HUN", "6.3575", "Ó, Allah (ﷻ), esküszöm Neked, hogy találkozom az ellenséggel, és ők megölnek, felvágják hasamat, levágják orromat és fülemet. Akkor Te megkérdezed tőlem: „Miért tették ezt veled?\" És én azt felelem: „Az Irántad való szeretetem miatt.\"⁵⁰",
      "Ó, Allah (ﷻ), kérve kérlek: hadd találkozzam holnap az ellenséggel, és öljenek meg, vágják fel hasamat, vágják le orromat és fülemet. Akkor Te megkérdezed tőlem: „Miért tették ezt veled?\" És én azt felelem: „Teérted.\"⁵⁰"),
    E("ENG", "6.3575", "O Allāh (ﷻ), I swear by you that I shall meet the enemy and they will kill me, cut open my stomach and cut off my nose and ears. Then you will ask me, \"Why was that done to you? And I shall reply, \"On account of my love for you.⁵⁰",
      "O Allāh (ﷻ), I adjure You: let me meet the enemy tomorrow and let them kill me, cut open my stomach and cut off my nose and ears. Then You will ask me, \"Why was that done to you?\" And I shall reply, \"For You.\"⁵⁰"),
    E("HUN", "6.3577", "és az iszlámnak nem lesz erős hadereje, és a zsarnokság sem vétetik le hátáról másképp,", "és az iszlám épülete sem emelkedik, a zsarnokság sem hárul el róla másképp,"),
    E("ENG", "6.3577", "and Islām will not have a strong force established for it nor will tyranny be removed from its back except", "and no edifice will rise for Islām, nor will tyranny be lifted from it, except"),
    E("HUN", "6.3579", "és Abū Ubādah föléje hajolva fogaival húzta ki őket.", "és Abū 'Ubādah [így az arab eredetiben; a hagyomány szerint Abū 'Ubaydah ibn al-Jarrāḥ volt — a ford.] föléje hajolva fogaival húzta ki őket."),
    E("ENG", "6.3579", "and Abū Ubādah leaned over him and pulled them out with his teeth.", "and Abū 'Ubādah [thus in the Arabic original; according to the reports it was Abū 'Ubaydah ibn al-Jarrāḥ — translator's note] leaned over him and pulled them out with his teeth."),
    E("HUN", "6.3581", "„Soha többé nem lesz senkim, aki olyan, mint te.", "„Soha nem ér még egyszer olyan veszteség, mint a te elvesztésed."),
    E("ENG", "6.3581", "\"I shall never have anyone like you again.", "\"I shall never be struck by a loss like yours."),
    E("HUN", "6.3601", "és egy gyors utalás arra elegendő leckét tartalmaz, hogy emlékeztesse őket", "és az azonnali megtorlásban elegendő lecke van, hogy emlékeztesse őket"),
    E("ENG", "6.3601", "and a quick reference to that contains a sufficient lesson to remind them", "and the immediate retribution contains a sufficient lesson to remind them"),
    E("HUN", "6.3603", "(Rendszerek múltak el előttetek.", "(Már elmúltak előttetek [a népeket sújtó] törvényszerűségek."),
    E("HUN", "6.3603b", "Ne lankadjatok és ne szomorkodjatok, mert felülkerekedtek rajtuk, ha [igaz] hívők vagytok.)", "Ne lankadjatok és ne szomorkodjatok, hiszen ti lesztek felül, ha [igaz] hívők vagytok.)"),
    E("HUN", "6.3611", "Az érző emberek szégyellnek", "Az értelmes emberek szégyellnek"),
    E("ENG", "6.3611", "People of feeling are ashamed", "People of understanding are ashamed"),
    E("HUN", "6.3617", "Mohamed (ﷺ) Allah szolgájaként és Küldötteként (ﷺ) gyűjtötte", "Mohamed (ﷺ) Allah (ﷻ) szolgájaként és Küldötteként gyűjtötte"),
    E("ENG", "6.3617", "as a servant and Messenger of Allāh (ﷺ),", "as a servant and Messenger of Allāh (ﷻ),"),
    E("HUN", "6.3621", "Ha a badri ütközet a hitetlenek elidegenedését okozta,", "Ha a badri ütközet a hitetlenek megalázására szolgált,"),
    E("ENG", "6.3621", "If the Battle of Badr caused the alienation of the unbelievers,", "If the Battle of Badr served to humiliate the unbelievers,"),
]
