# Ch6 part 6 (Uḥud vértanúi → … → Banū al-Muṣṭaliq) — see opus55-findings.md "Ch6 part 6"
from apply import E

EDITS = [
    E("HUN", "6.3659", "»Hamarosan eltávozom közületek. Előttetek járok. Találkozóhelyetek a (paradicsomi) forrás lesz, és onnan, ahol most állok, látom azt.", "»Én előttetek járok, mint előfutárotok, és tanú vagyok felettetek. Találkozóhelyetek a Medence (al-Ḥawḍ) lesz, és innen, ahol most állok, látom azt."),
    E("ENG", "6.3659", "\"I shall soon be gone from you. I am over you. Your meeting-place will be the spring (of paradise) and I can see it from where I stand now.", "'I go ahead of you as your forerunner, and I am a witness over you. Your meeting-place will be the Pool (al-Ḥawḍ), and I can see it from where I stand now."),
    E("ENG", "6.3659b", "that you will rival one another for it.\"⁵⁵", "that you will rival one another for it.'\"⁵⁵"),
    E("HUN", "6.3663a", "és erőt mutassanak, elrettentve minden leendő támadót. Az uḥudi vereséget", "és erőt mutassanak, elrettentve minden leendő támadót — ahogy a költő mondja:\n\n*Kárörvendőim előtt szilárdnak mutatom magam, hogy lássák:*\n\n*a sors csapásai alatt nem roppanok meg.*\n\nAz uḥudi vereséget"),
    E("ENG", "6.3663a", "and make a show of strength so as to deter any would-be attackers. The defeat at Uḥud", "and make a show of strength so as to deter any would-be attackers — as the poet says:\n\n*I show the gloaters my fortitude, that they may see*\n\n*I do not crumble under the blows of fate.*\n\nThe defeat at Uḥud"),
    E("HUN", "6.3663b", "és a hitetlenek arról kezdtek beszélni, hogy Allah elhagyta Prófétáját (ﷺ).", "és a hitetlenek arról kezdtek beszélni, hogy az ég cserben hagyta az Allah által küldött Prófétát (ﷺ)."),
    E("ENG", "6.3663b", "and the nonbelievers began talking of Allāh's desertion of his Prophet (ﷺ).", "and the unbelievers began talking of heaven's desertion of the Prophet (ﷺ) sent by Allāh."),
    E("HUN", "6.3671", "Ezzel az esettel kapcsolatban a következő āyāt nyilatkoztatott ki:\n\n(Azok, akiknek az emberek azt mondták:",
      "Erről a sikeres felvonulásról, és azokról, akik sebeik fájdalma és kimerültségük ellenére is részt vettek benne, a csüggesztés ellenére szilárdak maradtak, és Allahban (ﷻ) bíztak, a következő āyāt nyilatkoztatott ki:\n\n(Azok, akik a sebesülés után is engedtek Allah és a Küldött hívásának — azok közül, akik jót cselekszenek és óvakodnak [a rossztól], nagy jutalom jár nekik. Azok, akiknek az emberek azt mondták:"),
    E("HUN", "6.3673", "és Allah végtelen bőkezűségű.) (Korán 3: 173–174)", "és Allah végtelen bőkezűségű.) (Korán 3: 172–174)"),
    E("ENG", "6.3671", "Concerning this incident the following āyah was revealed:\n\n(Those to whom men said:",
      "Concerning this successful show of strength, and those who took part in it despite the pain of their wounds and their exhaustion, stood firm against discouragement and trusted in Allāh (ﷻ), the following āyāt were revealed:\n\n(As for those who heard the call of Allāh and His messenger after the harm befell them; for such of them as do right and ward off [evil], there is great reward. Those to whom men said:"),
    E("ENG", "6.3673", "and Allāh is of infinite bounty.) (Qur'ān 3: 173-174)", "and Allāh is of infinite bounty.) (Qur'ān 3: 172-174)"),
    E("HUN", "6.3681", "Bár Khālid ibn Sufyān al Hudhalī haderőt próbált gyűjteni a muszlimok megtámadására, a Próféta (ﷺ) 'Abdullāh ibn Anīst küldte utána,", "Khālid ibn Sufyān al-Hudhalī haderőt próbált gyűjteni a muszlimok megtámadására, de a Próféta (ﷺ) 'Abdullāh ibn Unaysot küldte utána,"),
    E("ENG", "6.3681", "Although Khālid ibn Sufyān al Hudhalī attempted to gather a force to attack the Muslims the Prophet (ﷺ) dispached 'Abdullāh ibn Anīs after him,", "Khālid ibn Sufyān al-Hudhalī attempted to gather a force to attack the Muslims, but the Prophet (ﷺ) dispatched 'Abdullāh ibn Unays after him,"),
    E("HUN", "6.usfan", "'Asafān", "'Usfān", count=2),
    E("ENG", "6.usfan", "'Asafān", "'Usfān", count=2),
    E("HUN", "6.3713a", "Abū Barā 'Āmir ibn Māliknak (رضي الله عنه), a „gerelyhajítóként\" ismert férfinak", "Abū Barā' 'Āmir ibn Māliknak, a „lándzsahegyekkel játszóként\" (Mulā'ib al-Asinnah) ismert férfinak"),
    E("ENG", "6.3713a", "Abū Barā (رضي الله عنه) 'Āmir ibn Mālik (رضي الله عنه), known as the spear-thrower,", "Abū Barā' 'Āmir ibn Mālik, known as Mulā'ib al-Asinnah (\"he who plays with spearheads\"),"),
    E("HUN", "6.3713b", "Abū Barā azonban kezességet vállalt", "Abū Barā' azonban kezességet vállalt"),
    E("ENG", "6.3713b", "However, Abū Barā undertook", "However, Abū Barā' undertook"),
    E("HUN", "6.maunah1", "Ma'unához", "Ma'ūnahhoz"),
    E("HUN", "6.maunah2", "Ma'unánál", "Ma'ūnahnál", count=3),
    E("HUN", "6.maunah3", "Ma'una-i", "Ma'ūnah-i"),
    E("HUN", "6.maunah4", "Ma'ūnához", "Ma'ūnahhoz"),
    E("ENG", "6.maunah1", "Ma'unah", "Ma'ūnah", count=4),
    E("ENG", "6.maunah2", "Ma'una", "Ma'ūnah", count=1),
    E("HUN", "6.3719", "A recitálók nyomában két férfi haladt, akik nem voltak szemtanúi ennek a tragédiának. Egyikük 'Amr ibn Umayyah al Damri volt. A szomorú hírről csak a tábor felé szálló, s a homokon szétszórt holttestek felett körözõ vadmadárrajokból",
      "A recitálók legelésző tevéinél volt két férfi, akik nem voltak szemtanúi ennek a tragédiának. Egyikük 'Amr ibn Umayyah al-Ḍamrī volt. A szomorú hírről csak a tábor felé szálló, s a homokon szétszórt holttestek felett köröző vadmadárrajokból"),
    E("ENG", "6.3719", "On the trail of the reciters were two men who did not witness this tragedy. One of them was 'Amr ibn Umayyah al Damri.", "With the reciters' grazing camels were two men who did not witness this tragedy. One of them was 'Amr ibn Umayyah al-Ḍamrī."),
    E("HUN", "6.3731a", "akiket 'Āmir fiainak vélt,", "akiket a Banū 'Āmir törzsbelinek vélt,"),
    E("ENG", "6.3731a", "whom he thought to be the sons of 'Āmir,", "whom he thought to be of the Banū 'Āmir,"),
    E("HUN", "6.3731b", "és Te velünk.\"⁵⁹ Azután így szólt 'Amrhoz: „Megöltél két embert, és én bizony megfizetem vérdíjukat.\"", "és Te velünk.\" Azután így szólt 'Amrhoz: „Megöltél két embert, és én bizony megfizetem vérdíjukat.\"⁵⁹"),
    E("ENG", "6.3731b", "and You with us.⁵⁹ Then he said to 'Amr: \"You have killed two men, and I shall indeed pay their blood money.\"", "and You with us. Then he said to 'Amr: \"You have killed two men, and I shall indeed pay their blood money.\"⁵⁹"),
    E("HUN", "6.3749", "a muszlimokat még kiszolgáltatottabbá tette az orgyilkosság és az árulás bűntetteivel szemben, amelyeknek immár egyénileg és közösségileg is ki voltak téve.", "a muszlimokat még érzékenyebbé tette az orgyilkosság és az árulás bűntetteire, amelyeknek immár csoportosan és egyénileg is ki voltak téve."),
    E("ENG", "6.3749", "had made the Muslims more susceptible to the crimes of assassination and treachery, to which they were now exposed individually and collectively.", "had made the Muslims more sensitive to the crimes of assassination and treachery, to which they were now exposed in groups and as individuals."),
    E("HUN", "6.3751", "az egész Al-Hashr szúra", "az egész Al-Ḥashr szúra"),
    E("ENG", "6.3751", "the whole of Sūrat Al-Hashr", "the whole of Sūrat Al-Ḥashr"),
    E("HUN", "6.3761", "Most jött el a próba: melyikük méltóbb a fennmaradásra.", "Joggal indult hát ki Mohamed (ﷺ) és társai, hogy szembenézzenek Abū Sufyānnal és népével, és még egyszer megforgassák a háború malomkövét, míg el nem dől, melyik fél jár a helyesebb úton, és melyik méltóbb a fennmaradásra."),
    E("ENG", "6.3761", "Now was the test to see which of the two was more worth of survival.", "Muhammad (ﷺ) and his Companions had every right to go out to face Abū Sufyān and his people and turn the millstone of war once more, until it was settled which of the two parties was better guided and more worthy of survival."),
    E("HUN", "6.3765a", "Így Abū Sufyān alig ért Dhahranba,", "Így Abū Sufyān alig ért al-Ẓahrānba,"),
    E("ENG", "6.3765a", "Thus Abū Sufyān had hardly reached Dhahran", "Thus Abū Sufyān had hardly reached al-Ẓahrān"),
    E("HUN", "6.3765b", "amelyben fákat növesztetek és tejet isztok.", "amelyben a bokrokon legeltettek, és tejet isztok."),
    E("ENG", "6.3765b", "only a year of fertility will be beneficial for you. In which you grow trees and drink milk.", "only a fertile year will do for you, in which you graze [your herds] on the shrubs and drink milk."),
    E("HUN", "6.3769", "## Dumat al Jandal", "## Dūmat al-Jandal"),
    E("ENG", "6.3769", "## Dumat al Jandal", "## Dūmat al-Jandal"),
    E("HUN", "6.3773", "Ez a hidzsra utáni ötödik év Rabi'-1 havában történt.", "Ez a hidzsra utáni ötödik év Rabī' al-Awwal havában történt."),
    E("ENG", "6.3773", "This was in Rabi'I-1 of the fifth year after the Hijrah.", "This was in Rabī' al-Awwal of the fifth year after the Hijrah."),
    E("HUN", "6.3775", "azokkal az eszközökkel együtt, amelyekkel az erős kérkedhet.", "azok mellett az eszközök mellett, amelyekkel az erősek nyíltan élnek."),
    E("ENG", "6.3775", "along with the means about which the strong can boast.", "alongside the means which the strong use openly."),
    E("HUN", "6.3789", "Azután népéhez fordult, amely még őrzött némi méltóságot, korholva őket,", "Azután népéhez fordult — akik körében még volt némi tekintélye —, korholva őket,"),
    E("ENG", "6.3789", "Then he turned to his people, who still maintained some dignity criticizing them", "Then he turned to his people — among whom he still had some standing — criticizing them"),
]
