# Ch6 part 7 (Ifk → Árok) — see opus55-findings.md "Ch6 part 7"
from apply import E

EDITS = [
    E("HUN", "6.3819", "Azokban a napokban a feleségek keveset ettek; nem szerették a húst, mert meghíztak volna tőle.", "Azokban a napokban az asszonyok csak annyit ettek, amennyi épp életben tartotta őket; a hús még nem tette nehézzé őket."),
    E("ENG", "6.3819", "In those days the wives would eat lightly; they did not like meat because they would put on weight.", "In those days the women ate only a bare minimum; meat had not yet made them heavy."),
    E("HUN", "6.3831", "Egyszerű nép voltunk, házainkban nem voltak olyan árnyékszékek, amilyenek az idegeneknél.", "Arabok voltunk, házainkban nem voltak olyan árnyékszékek, amilyenek a nem araboknál."),
    E("ENG", "6.3831", "We were a simple people and our houses did not contain those closets which the foreigners had.", "We were Arabs and our houses did not contain those closets which the non-Arabs had."),
    E("HUN", "6.usayd", "Usayd ibn Hudayr", "Usayd ibn Ḥuḍayr", count=2),
    E("ENG", "6.usayd", "Usayd ibn Hudayr", "Usayd ibn Ḥuḍayr", count=2),
    E("HUN", "6.3853", "„Allah Küldötte (ﷺ), ha az Ausból valók,", "„Allah Küldötte (ﷺ), ha az Awsból valók,"),
    E("ENG", "6.3853", "\"Messenger of Allāh (ﷺ), if they are from the Aus,", "\"Messenger of Allāh (ﷺ), if they are from the Aws,"),
    E("HUN", "6.3859", "„Allah Küldötte (ﷺ), ők a te családod, és ez hazugság és koholmány.\"", "„Allah Küldötte (ﷺ), ők a te családod, és csak jót tudunk róluk; ez pedig hazugság és koholmány!\""),
    E("ENG", "6.3859", "Usāmah spoke only good, saying, Messenger of Allāh (ﷺ), they are your family, and this is a lie and a falsehood.\"", "Usāmah spoke only good, saying: \"Messenger of Allāh (ﷺ), they are your family, and we know nothing of them but good; this is a lie and a falsehood!\""),
    E("HUN", "6.3877", "azzal szemben, amit leírtok.«\"", "azzal szemben, amit leírtok.« (Korán 12: 18)\""),
    E("ENG", "6.3877", "Whose help is to be sought in that which you describe'.\"", "Whose help is to be sought in that which you describe' (Qur'ān 12: 18).\""),
    E("HUN", "6.3879", "Arra (ﷻ), akinek kezében 'Ā'ishah lelke van", "Arra, Akinek kezében 'Ā'ishah lelke van"),
    E("HUN", "6.3903a", "asszonyaikat és gyermekeiket Yathrib biztonságos magaslataira helyezték.", "asszonyaikat és gyermekeiket Yathrib megerősített tornyaiba helyezték."),
    E("ENG", "6.3903a", "they had put their women and children on the secured hills of Yathrib.", "they had put their women and children in the fortified towers of Yathrib."),
    E("HUN", "6.3903b", "háttal a Sala dombjának,", "háttal a Sal' hegyének,"),
    E("ENG", "6.3903b", "with their backs to the hill of Sala,", "with their backs to the hill of Sal',"),
    E("HUN", "6.3909", "és közben ezt zengte: »Allahra (ﷻ), ha nem volna Allah (ﷻ), nem vezéreltetnénk, nem adakoznánk és nem imádkoznánk.", "és közben ezt zengte:\n\n*»Allahra (ﷻ), ha nem volna Allah (ﷻ), nem vezéreltetnénk, nem adakoznánk és nem imádkoznánk.*"),
    E("ENG", "6.3909", "and he was chanting: \"By Allāh (ﷻ), if it were not for Allāh (ﷻ) we should not be guided nor should we be charitable nor pray.", "and he was chanting:\n\n*\"By Allāh (ﷻ), if it were not for Allāh (ﷻ) we should not be guided nor should we be charitable nor pray.*"),
    E("HUN", "6.3925", "Örüljetek hát a jó hírnek!\" A muszlimok összegyűltek, és azt mondták: „Dicsőség Allahnak (ﷻ). Igaz ígéret.\"", "Örüljetek hát a jó hírnek!\" A muszlimok megörültek a jó hírnek, és azt mondták: „Hála és dicséret Allahnak (ﷻ)! Igaz ígéret ez.\""),
    E("ENG", "6.3925", "So rejoice at the good news. The Muslims rallied and said: \"Praise be to Allāh (ﷻ). A true promise.\"", "So rejoice at the good news!\" The Muslims rejoiced at the good news and said: \"Praise be to Allāh (ﷻ)! A true promise.\""),
    E("HUN", "6.3935", "olyanok lettek, mint egy magányos sziget a hurrikán közepén, amely éjjel-nappal pusztulással fenyegette őket.", "olyanok lettek, mint egy magányos sziget az áradat közepén, amely éjjel-nappal elnyeléssel fenyegette őket."),
    E("ENG", "6.3935", "like an remote island in the middle of a hurricane which threatened to destroy it by day or night.", "like an isolated island in the middle of a flood which threatened to drown it by day or night."),
    E("HUN", "6.3939a", "és Ḍirar ibn al-Khaṭṭāb", "és Ḍirār ibn al-Khaṭṭāb"),
    E("ENG", "6.3939a", "and Ḍirar ibn al-Khaṭṭāb", "and Ḍirār ibn al-Khaṭṭāb"),
    E("HUN", "6.3939b", "Azután az árok egy sekély részét keresték meg,", "Azután az árok egy keskeny részét keresték meg,"),
    E("ENG", "6.3939b", "Then they looked for a shallow part of the ditch", "Then they looked for a narrow part of the ditch"),
    E("HUN", "6.3941", "'Amr ibn 'Abdul Wuddhoz, a bátor lóidomárhoz:", "'Amr ibn 'Abdul Wuddhoz, a bátor, híres lovashoz:"),
    E("ENG", "6.3941", "'Amr ibn 'Abdul Wudd, the brave horse trainer:", "'Amr ibn 'Abdul Wudd, the brave, renowned horseman:"),
    E("HUN", "6.3947", "'Amr így felelt: „És miért, ó, unokatestvérem? Mert Istenre, nem kívánlak megölni.\"", "'Amr így felelt: „És miért, öcsém? Mert Istenre, nem kívánlak megölni\" — lebecsülve őt."),
    E("ENG", "6.3947", "'Amr replied: \"And why, O cousin of mine, for by God I do not wish to kill you.\"", "'Amr replied: \"And why, O son of my brother? For by God I do not wish to kill you\" — making little of him."),
    E("HUN", "6.3951", "Erre 'Amr haragra gerjedt. Leszállt lováról, szembefordult 'Alīval (رضي الله عنه),", "Erre 'Amr haragra gerjedt. Leugrott lováról, megbénította és arcul csapta, majd szembefordult 'Alīval (رضي الله عنه),"),
    E("ENG", "6.3951", "At this, 'Amr became enraged. Dismounting from his horse he faced 'Alī (رضي الله عنه),", "At this, 'Amr became enraged. He leapt from his horse, hamstrung it and struck its face, then faced 'Alī (رضي الله عنه),"),
    E("HUN", "6.3953", "'Umar ibn Abi Salāmah", "'Umar ibn Abī Salamah"),
    E("ENG", "6.3953", "'Umar ibn Abi Salāmah", "'Umar ibn Abī Salamah"),
    E("HUN", "6.3959", "és nem segíti egyetlen ellenségüket sem.", "és nem segíti egyetlen ellenségüket sem — bárcsak kitartott volna e szándéka mellett!"),
    E("ENG", "6.3959", "and not assist any enemy of theirs.", "and not assist any enemy of theirs — would that he had kept to this resolve!"),
    E("HUN", "6.3971", "veled eszem a kukoricadarádból!", "veled eszem a búzakásádból!"),
    E("ENG", "6.3971", "I shall eat your cornmeal with you!", "I shall eat your porridge of coarse-ground wheat with you!"),
    E("HUN", "6.3999", "Ahogy a költő mondja: „Hátramaradtam, hogy megőrizzem az életet, de nem találtam magamnak olyan életet, mint ha előrenyomultam volna.\"", "Ahogy a költő mondja:\n\n*Hátramaradtam, hogy életemet megőrizzem, de nem találtam*\n\n*magamnak olyan életet, mint ha előrenyomultam volna.*"),
    E("ENG", "6.3999", "As the poet says: \"I kept back In order to preserve life, but I did not find for myself any life such as if I were to advance.\"", "As the poet says:\n\n*I held back to preserve my life, but I found*\n\n*no life for myself like that of pressing forward.*"),
]
