# Ch6 part 8 (Árok vége → Quraydhah → Abū Rāfi' → 5. év vége) + Ch6 footnote spot-checks — see opus55-findings.md
from apply import E

EDITS = [
    E("HUN", "6.4021", "Úgy tűnik, Sa'd sebe súlyos volt, mert ő nem az az ember volt, aki féli a halált. Mélyen vágyott", "Úgy tűnik, Sa'd sebe súlyos volt. Sa'd nem az az ember volt, aki féli a halált, de mélyen vágyott"),
    E("ENG", "6.4021", "It appears that Sa'd's wound was severe, for he was not a man to fear death. He was deeply desirous", "It appears that Sa'd's wound was severe. Sa'd was not a man to fear death, but he was deeply desirous"),
    E("HUN", "6.4033", "'Abdullāh ibn Awfa is elbeszélte,", "'Abdullāh ibn Awfā [így az arab eredetiben; helyesen Ibn Abī Awfā — a ford.] is elbeszélte,"),
    E("ENG", "6.4033", "'Abdullāh ibn Awfa narrated", "'Abdullāh ibn Awfā [thus in the Arabic original; correctly Ibn Abī Awfā — translator's note] narrated"),
    E("HUN", "6.4045", "Nem is csoda, hiszen Ḥamzah nővére volt!", "Nem is csoda, hiszen Ḥamzah testvére volt!"),
    E("HUN", "6.naim2", "Na'im", "Nu'aym", count=3),
    E("ENG", "6.naim2a", "what Na'im had told them", "what Nu'aym had told them", count=2),
    E("ENG", "6.naim2b", "Na'im set off for the Quraydhah", "Nu'aym set off for the Quraydhah"),
    E("HUN", "6.4065", "Marháink és juhaink fogytán vannak.", "Tevéink és lovaink pusztulnak."),
    E("ENG", "6.4065", "Our cattle and sheep are being consumed.", "Our camels and horses are perishing."),
    E("HUN", "6.4087", "marháitok és juhaitok elhullottak;", "lovaitok és tevéitek elpusztultak;"),
    E("ENG", "6.4087", "your cattle and sheep have died", "your horses and camels have perished"),
    E("HUN", "6.4127a", "éppúgy szükségesek, mint bizonyos meghatározott utasítások az egészség megőrzéséhez.", "éppúgy szükségesek, mint a test megőrzéséhez szükséges táplálékok."),
    E("ENG", "6.4127a", "just as some specific instructions are needed for the safeguarding of one's health.", "just as the necessary foods are needed for the safeguarding of the body."),
    E("HUN", "6.4127b", "még ha az történetesen az ima volt is.\n", "még ha az történetesen az ima volt is. Az ima idejének határai elolvadnak a harc szükségletei előtt.\n"),
    E("ENG", "6.4127b", "even if it happened to be prayer.\n", "even if it happened to be prayer. The limits of prayer-time melt away before the necessities of fighting.\n"),
    E("ENG", "6.4129", "the merchant who neglects to invest his wealth and the employer who neglects to invest his wealth and the employee who neglects his work", "the merchant who neglects to invest his wealth and the employee who neglects his work"),
    E("HUN", "6.4137", "„Ó, Abū Qāsim\"", "„Ó, Abū al-Qāsim\""),
    E("ENG", "6.4137", "\"O Abū Qāsim,\"", "\"O Abū al-Qāsim,\""),
    E("HUN", "6.4139", "és tökéletes példaképnek írják le az embereket, amikor félnek — mindezt csakis saját hasznukért.", "és a legfőbb eszményekre emlékeztetik az embereket, amikor félnek — csakis azért, hogy egyedül ők húzzanak belőlük hasznot."),
    E("ENG", "6.4139", "and they describe people as the perfect example when they are afraid and for no other reason than their personal gain.", "and they remind people of the highest ideals when they are afraid — only so that they alone may benefit from them."),
    E("HUN", "6.4189", "*Életedre, Ibn Akhtab nem hibáztatta magát,*\n\n*De akit Allah (ﷻ) elhagy, az elhagyatott.*\n\n*Harcolt, míg el nem érte határát,*\n\n*És bajt kavart.*\n\n*És minden bajkeverő dicsőségre tör.*",
      "*Életedre, Ibn Akhṭab nem hibáztatta önmagát,*\n\n*de akit Allah (ﷻ) elhagy, az elhagyatott.*\n\n*Addig küzdött, míg lelkének meg nem adott minden mentséget,*\n\n*és dicsőséget keresve mindent megmozgatott.*"),
    E("ENG", "6.4189", "*By your life, Ibn Akhtab did not blame himself,*\n\n*But whoever deserts Allāh (ﷻ) is deserted.*\n\n*He fought until he reached his limit,*\n\n*And stirred up trouble.*\n\n*And every troublemaker seeks glory.*",
      "*By your life, Ibn Akhṭab did not blame himself,*\n\n*but whoever Allāh (ﷻ) forsakes is forsaken.*\n\n*He strove until he had given his soul every excuse,*\n\n*and went to every length in seeking glory.*"),
    E("HUN", "6.4207", "a Quraydhah zsidai felől,", "a Quraydhah zsidói felől,"),
    E("HUN", "6.4211", "'Abdullāh ibn 'Atikot", "'Abdullāh ibn 'Atīkot"),
    E("ENG", "6.4211", "'Abdullāh ibn 'Atik as", "'Abdullāh ibn 'Atīk as"),
    E("HUN", "6.4213a", "Ibn Abi al Haqīq házát", "Ibn Abī al-Ḥuqayq házát"),
    E("ENG", "6.4213a", "Ibn Abi al Haqīq", "Ibn Abī al-Ḥuqayq"),
    E("HUN", "6.4213b", "'Abdullāh ibn 'Ātik azt mondta", "'Abdullāh ibn 'Atīk azt mondta"),
    E("ENG", "6.4213b", "'Abdullāh ibn 'Ātik told", "'Abdullāh ibn 'Atīk told"),
    E("HUN", "6.4225", "Salāmah ibn al Akwa'", "Salamah ibn al-Akwa'"),
    E("ENG", "6.4225", "Salāmah ibn al Akwa'", "Salamah ibn al-Akwa'"),
    E("HUN", "6.4227a", "A férfi azonban kereszténnyé lett, és ott meghalt,", "A férfi azonban hitehagyott lett, és ott meghalt,"),
    E("ENG", "6.4227a", "He, however, became a Christian and died there,", "He, however, apostatized and died there,"),
    E("HUN", "6.4227b", "Elküldte hát ajánlatát a négusnak, és őt tette meg megbízottjává e szerződésben.", "Elküldte hát a négusnak az asszony jegyajándékát (mahr), és őt tette meg megbízottjává a házasság megkötésében."),
    E("ENG", "6.4227b", "Thus he sent his offer to the Negus and made him his agent in this contract.", "Thus he sent her dower (mahr) to the Negus and made him his proxy in contracting the marriage."),
    E("HUN", "6.4231", "'Amr ibn al 'As ebben", "'Amr ibn al-'Āṣ ebben"),
    E("ENG", "6.4231", "'Amr ibn al 'As became", "'Amr ibn al-'Āṣ became"),
    # Ch6 footnotes
    E("HUN", "6.f15", "Ibn Ḥibāb tekintélyére hivatkozva mursal formában,", "Ibn Shihāb (Al-Zuhrī) tekintélyére hivatkozva mursal formában,"),
    E("ENG", "6.f15", "on the authority of Ibn Ḥibāb in mursal form", "on the authority of Ibn Shihāb (Al-Zuhrī) in mursal form"),
    E("HUN", "6.f35", "azzal a különbséggel, hogy Zubayr ismert a tadlīsról.", "azzal a különbséggel, hogy Abū al-Zubayr ismert a tadlīsról."),
    E("ENG", "6.f35", "except that Zubayr is known for tadlīs.", "except that Abū al-Zubayr is known for tadlīs."),
    E("HUN", "6.f50", "Abū-Dhahabī egyetértett vele", "Al-Dhahabī egyetértett vele"),
    E("ENG", "6.f50", "Abū-Dhahabī agreed with him", "Al-Dhahabī agreed with him"),
    E("HUN", "6.f63", "⁶³ Ez nem helytálló. Ibn Hishām rámutatott erre Sīrájában, amikor lánc nélkül idézte az elbeszélést, és azt mondta: „A hiteles változat az, hogy a Próféta (ﷺ) a megkívánt összeg megfizetésével szabadította fel, és úgy vette feleségül, hogy nem kérte meg apjától, mivel fogoly volt.\" Ezt Ibn Ishāq beszélte el 'Ā'ishah tekintélyére hivatkozva, hiteles lánccal. Elbeszélte Ahmad és Ibn Hishām is egy másik lánccal, és ez a változat tartalmazza a foglyok szabadon bocsátásának egész történetét.",
      "⁶³ Ez nem helytálló, amire Ibn Hishām is utalt Sīrájában: ezt az elbeszélést lánc nélkül idézte, és ezzel vezette be: „Azt mondják…\" A hiteles változat az, hogy a Próféta (ﷺ) kifizette az asszony szabadulási díját (kitābah), és úgy vette feleségül, hogy nem kérte meg apjától, mivel fogoly volt — ahogyan Ibn Isḥāq hiteles lánccal elbeszélte 'Ā'ishah (رضي الله عنها) tekintélyére hivatkozva. Az ő útján beszélte el Aḥmad és Ibn Hishām is, és elbeszélésükben benne van a foglyok szabadon bocsátásának története."),
    E("ENG", "6.f63", "⁶³ This is not correct. Ibn Hishām pointed this out in his Sīrah when he quoted the narration without a chain and said \"The authentic version is that the Prophet (ﷺ) set her free by paying the required sum, and married her without proposing to her father since she was a prisoner.\" This is narrated by Ibn Ishāq on the authority of 'Ā'ishah with an authentic chain. It is also narrated by Ahmad and Ibn Hishām by another chain and this version contains all the story of the release of the prisoners.",
      "⁶³ This is not correct, as Ibn Hishām indicated in his Sīrah: he quoted this narration without a chain and introduced it with \"It is said…\" The authentic version is that the Prophet (ﷺ) paid off her contract of manumission (kitābah) and married her without proposing to her father, since she was a captive — as Ibn Isḥāq narrated with an authentic chain on the authority of 'Ā'ishah (رضي الله عنها). Aḥmad and Ibn Hishām narrated it by way of him, and their narration contains the story of the release of the prisoners."),
    E("HUN", "6.f74", "„a háború megtévesztés\" — hiteles, mert Muszlim és Bukhārī beszélte el.", "„a háború megtévesztés\" — hiteles és mutawātir (számos független láncon áthagyományozott): a két sejk beszélte el Jābir és Abū Hurairah hadíszaként, és mások is."),
    E("ENG", "6.f74", "\"War is deception\" is authentic, for it is narrated by Muslim and Bukhārī.", "\"War is deception\" is authentic and mutawātir (transmitted through numerous independent chains): the two Sheikhs narrated it as a ḥadīth of Jābir and of Abū Hurairah, and others did too."),
]
