# Ch7 part 1 (Ḥudaybiyah) — see opus55-findings.md "Ch7 — part 1"
from apply import E

EDITS = [
    E("HUN", "7.4435", "A háború megrontotta őket.", "A háború felfalta őket."),
    E("ENG", "7.4435", "War has corrupted them.", "War has devoured them."),
    E("HUN", "7.4437", "és egy kietlen, sáros csapáson vezette őket,", "és egy rögös, kopár csapáson vezette őket,"),
    E("ENG", "7.4437", "and he took them along a desolate, muddy track", "and he took them along a rugged, barren track"),
    E("HUN", "7.4453", "Azután Makraz ibn Ḥafst küldték,", "Azután Mikraz ibn Ḥafṣot küldték,"),
    E("ENG", "7.4453", "Then they sent Makraz ibn Ḥafs,", "Then they sent Mikraz ibn Ḥafṣ,"),
    E("HUN", "7.4459", "az aḥābīsh (zsoldosok) minden", "az aḥābīsh (a Quraish szövetséges nemzetségei) minden"),
    E("ENG", "7.4459", "the Ahabish (mercenaries).", "the Aḥābīsh (the allied clans of the Quraish)."),
    E("HUN", "7.4471", "Abū Qahāfah fia,", "Abū Quḥāfah fia,"),
    E("ENG", "7.4471", "the son of Abū Qahafah", "the son of Abū Quḥāfah"),
    E("HUN", "7.4481", "„Te nyomorult! Hát nem éppen tegnap", "„Te áruló! Hát nem éppen tegnap"),
    E("ENG", "7.4481", "\"You wretch! Wasn't it only yesterday", "\"You treacherous one! Wasn't it only yesterday"),
    E("HUN", "7.4485", "Némelyikük csak azért nem ragaszkodott tovább ehhez, mert érezte, hogy a Quraish megátalkodott,", "Némelyikük csak azért mondta ki ezt nyíltan és nyomatékosan, mert érezte, hogy a Quraish gőgös,"),
    E("ENG", "7.4485", "Some of them only kept from insisting on this when they felt that the Quraish were being stubborn", "Some of them pressed this point openly only because they sensed that the Quraish were being arrogant"),
    E("HUN", "7.musayyib", "Sa'īd ibn al Musayyabhoz", "Sa'īd ibn al-Musayyibhoz"),
    E("ENG", "7.musayyib1", "I came to Sa'īd ibn al Musayyab", "I came to Sa'īd ibn al-Musayyib"),
    E("ENG", "7.musayyib2", "Sa'id ibn al Musayyab, who said", "Sa'īd ibn al-Musayyib, who said"),
    E("HUN", "7.4521", "amelyhez ellenségei folyamodtak azóta, hogy elűzték otthonából.", "amelyhez ellenségei folyamodtak azóta, hogy elzárták őt a Háztól (a Ka'bától)."),
    E("ENG", "7.4521", "to which his enemies had chosen to resort ever since they had expelled him from his home.", "to which his enemies had chosen to resort ever since they had barred him from the House (the Ka'bah)."),
    E("HUN", "7.4543", "és nem lesz sem titkos fenntartás, sem hitszegés.", "és nem lesz sem lopás, sem hűtlenség."),
    E("ENG", "7.4543", "and there will be no secret reservation or disloyalty.", "and there will be no theft and no treachery."),
    E("HUN", "7.4557", "aki átment hozzájuk, azok gonoszságától a muszlimok megmenekültek. Ami pedig az elnyomott muszlimokat illeti, a Quraish hamarosan tudomást szerez róluk, ahogyan tudomást szerzett az előttük lévőkről is,",
      "aki hitetlenként átment hozzájuk — Allah (ﷻ) ne hozza vissza! —, annak gonoszságától megmenekültek a muszlimok. Ami pedig az elnyomott muszlimokat illeti, a Quraish nem boldogul majd velük, ahogyan az előttük lévőkkel sem boldogult,"),
    E("ENG", "7.4557", "Those who went over the Muslims were saved from their evil. As for the oppressed Muslims, the Quraish would soon learn about them as they had learnt about those before them,",
      "Whoever went over to them as an unbeliever — may Allāh not bring him back! — the Muslims were spared his evil. As for the oppressed Muslims, the Quraish would be at their wits' end with them, as they had been helpless against those before them,"),
    E("HUN", "7.4561", "„Allah Küldötte (ﷺ), mit vársz tőlük? Menj ki,", "„Allah Küldötte (ﷺ), szeretnéd, hogy megtegyék? Menj ki,"),
    E("ENG", "7.4561", "\"Messenger of Allāh (ﷺ), what do you expect? Go out", "\"Messenger of Allāh (ﷺ), would you like that [done]? Go out"),
    E("HUN", "7.4567", "kivált, hogy a Quraish befagyasztotta haszonleső politikáját.", "kivált, hogy a Quraish mereven kitartott haszonleső politikája mellett, kereskedelmi ügyeivel volt elfoglalva, és nem igyekezett szövetségeseket szerezni."),
    E("ENG", "7.4567", "especially since the Quraish froze their opportunistic policies and concentrated, on the other hand, the Muslims expanded", "especially since the Quraish stuck rigidly to their opportunistic policies and concentrated on their trade, making no effort to win allies. The Muslims, on the other hand, expanded"),
    E("HUN", "7.4587", "Abū Baṣīr belátta, hogy Mekkában nincs számára hely, Medinában pedig nincs menedék. A tengerparthoz ment egy 'Ays nevű hely közelébe, és onnan fenyegette a Quraish karavánjait, amelyek a Saha útján haladtak át.",
      "Abū Baṣīr belátta, hogy Medinában nem maradhat, Mekkában pedig nincs biztonságban. A tengerparthoz ment egy al-'Īṣ nevű hely közelébe, és onnan fenyegette a Quraish karavánjait, amelyek a parti úton haladtak át."),
    E("ENG", "7.4587", "Abū Baṣīr realized that there was no place for him in Makkah and no refuge in Madīnah. He went to the seashore near a place called 'Ays, and from there he threatened the caravans of the Quraish which passed through the road of Saha.",
      "Abū Baṣīr realized that there was no staying for him in Madīnah and no safety for him in Makkah. He went to the seashore near a place called al-'Īṣ, and from there he threatened the caravans of the Quraish which passed along the coastal road."),
]
