# Ch7 part 2 (Újra a zsidókkal → Khaybar → abesszíniai visszatérők → beduinok → levelek) — see opus55-findings.md "Ch7 part 2"
from apply import E

EDITS = [
    E("HUN", "7.4613a", "félrevezették Mohamedet (ﷺ), és elutasították üzenetét. Elámította őket a Tórából örökölt méltóságuk,", "meghazudtolták Mohamedet (ﷺ), és elutasították üzenetét. Elámították őket a Tórából örökölt külsőségek,"),
    E("ENG", "7.4613a", "deceived Muhammad (ﷺ) and rejected his message. They were deluded by the honour which they had inherited from the Torah,", "called Muhammad (ﷺ) a liar and rejected his message. They were deluded by the husks which they had inherited from the Torah,"),
    E("HUN", "7.4615", "Az iszlám elleni gyűlölet összehozta az ostoba beduint a ravasz zsidóval.", "Az iszlám elleni gyűlölet összehozta az együgyű beduinokat és a Könyv népét, a zsidókat."),
    E("ENG", "7.4615", "The enmity against Islām brought together the stupid bedouin with the cunning Jews.", "The enmity against Islām brought together the simple-minded bedouin and the People of the Book, the Jews."),
    E("HUN", "7.4629", "Rémülten siettek vissza erődjeikbe.", "Rémülten siettek vissza erődjeikbe, ezt kiáltozva: „Mohamed és a sereg!\""),
    E("ENG", "7.4629", "They hurried back to their fortresss in dismay.", "They hurried back to their fortresses in dismay, crying: \"Muhammad and the army!\""),
    E("HUN", "7.4633", "„És Mūsā népéből van egy közösség, amely az igazsággal vezet, és aszerint ítél.\"", "(És Mūsā népéből van egy közösség, amely az igazsággal vezet, és aszerint ítél.) (Korán 7: 159)"),
    E("ENG", "7.4633", "\"And from the people of Moosā there is a group who guides by the truth and by it they judge.\"", "(And from the people of Moses there is a group who guides by the truth and by it they judge.) (Qur'ān 7: 159)"),
    E("HUN", "7.4639", "„Allah Küldötte (ﷺ)! Harcoljak ellenük, míg vissza nem vonulnak onnan?\"", "„Allah Küldötte (ﷺ)! Harcoljak ellenük, míg olyanok nem lesznek, mint mi?\""),
    E("ENG", "7.4639", "\"Messenger of Allāh (ﷺ)! should I fight them till they retreat from there?\"", "\"Messenger of Allāh (ﷺ)! Should I fight them until they become like us?\""),
    E("HUN", "7.4641", "„Haladj megállás nélkül, míg földjükre nem érsz,", "„Indulj, nyugodt lépésben, míg földjükre nem érsz,"),
    E("HUN", "7.4641b", "jobb neked, mintha halmokban állna aranyad.\"²⁵", "jobb neked, mintha vörös tevék (a legbecsesebb vagyon) volnának a tieid.\"²⁵"),
    E("ENG", "7.4641", "\"Keep going without a halt until you enter their quarters,", "\"Go forth at your ease until you reach their quarters,"),
    E("ENG", "7.4641b", "is better than if you were to have heaps of gold.\"²⁵", "is better for you than owning red camels (the most prized of wealth).\"²⁵"),
    E("HUN", "7.4643", "„Yā Manṣūr, amut, amut!\"", "„Yā Manṣūr, amit, amit!\" (Ó, győztes, ölj, ölj!)"),
    E("ENG", "7.4643", "\"Ya Manṣūr, amut, amut!\"", "\"Yā Manṣūr, amit, amit!\" (O victorious one, kill, kill!)"),
    E("HUN", "7.marhab", "Marhab", "Marḥab", count=4),
    E("ENG", "7.marhab", "Marhab", "Marḥab", count=4),
    E("HUN", "7.natah", "az Al Niṭāh nevű erődlánc", "az al-Naṭāh nevű erődlánc"),
    E("HUN", "7.huyayy", "Huyayy", "Ḥuyayy", count=1),
    E("ENG", "7.huyayy", "Huyayy", "Ḥuyayy", count=1),
    E("HUN", "7.hashraj", "Hashraj", "Ḥashraj", count=3),
    E("ENG", "7.hashraj", "Hashraj", "Ḥashraj", count=3),
    E("HUN", "7.4677", "„Tereld ki őket a nyílt mezőre, és hagyd ott őket. Allah (ﷻ) teljesíti helyetted a rád bízottakat.\"", "„Tereld el őket magadtól, és dobálj utánuk kavicsot: Allah (ﷻ) teljesíti helyetted a rád bízottakat.\""),
    E("ENG", "7.4677", "\"Lead them out into the open and leave them. Allāh (ﷻ) will discharge your trust for you.\"", "\"Drive them away from you and throw pebbles after them: Allāh (ﷻ) will discharge your trust for you.\""),
    E("HUN", "7.4733", "Ja'far és társai mintegy tíz évig maradtak Abesszíniában;", "Ja'far és társai tíz-egynéhány évig maradtak Abesszíniában;"),
    E("ENG", "7.4733", "Ja'far and his comrades had remained in Abyssinia for some ten years,", "Ja'far and his comrades had remained in Abyssinia for ten-odd years,"),
    E("HUN", "7.4763", "A muszlimok egyik legfontosabb lépése a Khaybarból való visszatérésük és a ḥudaybiyai szerződésben ígért pótló 'umrára Mekkába tett útjuk után az volt, hogy felderítő csapatokat küldtek ki Najd sivatagjaiba.",
      "A muszlimokat attól fogva, hogy a hetedik év Ṣafar havában visszatértek Khaybarból, egészen addig, amíg útra nem keltek a ḥudaybiyai szerződésben megszabott pótló 'umrára, leginkább az foglalkoztatta, hogy felderítő csapatokat küldjenek ki Najd sivatagjaiba."),
    E("ENG", "7.4763", "One of the most important actions of the Muslims after their return from Khaybar and their journey to Makkah for the compensatory 'Umrah as promised in the Treaty of Ḥudaybiyah was the dispatching of scouting parties in the deserts of Najd.",
      "From their return from Khaybar in Ṣafar of the seventh year until they set out for the compensatory 'Umrah fixed in the Treaty of Ḥudaybiyah, one of the most important concerns of the Muslims was the dispatching of scouting parties into the deserts of Najd."),
    E("HUN", "7.4771", "Gondolod, hogy a hithirdetőket magukra lehetett hagyni ilyen környezetben, hogy békében végezzék munkájukat?", "Gondolod, hogy a hithirdetők fegyvertelenül járhattak ilyen környezetben, amely vagyont és hitet egyaránt elragad?"),
    E("ENG", "7.4771", "Do you think that the missionaries could be left in such an environment to carry out their work in peace?", "Do you think that the missionaries could go about unarmed in such an environment, which snatches away both wealth and beliefs?"),
    E("HUN", "7.4783", "amelyek számos okból sötétségbe merültek.", "amelyek hosszú idők óta sötétségbe merültek."),
    E("ENG", "7.4783", "which had been submerged in-darkness for many reasons.", "which had been submerged in darkness for ages."),
    E("HUN", "7.4821", "Szíria kormányzója elolvasta", "Damaszkusz emírje elolvasta"),
    E("ENG", "7.4821", "The governor of Syria read", "The emir of Damascus read"),
    E("HUN", "7.4829", "Alexandria pátriárkája kedves választ küldött", "Al-Muqawqis kedves választ küldött"),
    E("ENG", "7.4829", "The Patriarch of Alexandria sent a kind reply", "Al-Muqawqis sent a kind reply"),
    E("HUN", "7.4837", "'Abdullāh fiának, Alexandria pátriárkájától:", "'Abdullāh fiának, Al-Muqawqistól, a koptok nagyjától:"),
    E("ENG", "7.4837", "son of 'Abdullāh, from the Patriarch of Alexandria:", "son of 'Abdullāh, from Al-Muqawqis, the great one of the Copts:"),
    E("HUN", "7.6139", "akit Alexandria pátriárkája küldött neki", "akit Al-Muqawqis küldött neki"),
    E("ENG", "7.6139", "by the Patriarch of Alexandria", "by Al-Muqawqis"),
]
