# Ch7 part 6 (Tabūk) — see opus55-findings.md "Ch7 part 6"; AR pp.310–316
from apply import E

EDITS = [
    # «عزم النبى أن يرسى العلائق… على دعائم مكينة» / dropped «يجب أن تتاح الفرص المعقولة…» / «يقاومه الإسلام بالقوة»
    E("HUN", "7f.1", "A Próféta (ﷺ) erősíteni akarta a kötelékeket az iszlám és a kereszténység között, de nem az iszlám rovására. Így nem fogadott el semmiféle alkudozást abban a kérdésben, hogy hithirdetői szabadon tárhassák-e üzenetüket az emberiség elé, az elfogadás vagy elutasítás választásával. Az iszlám határozottan ellenezte hithirdetőinek megölését és munkájuk elé akadályok emelését.",
      "A Próféta (ﷺ) elhatározta, hogy az iszlám és a kereszténység közötti viszonyt szilárd alapokra helyezi. Nem fogadott el semmiféle alkudozást abban a kérdésben, hogy hithirdetői szabadon tárhassák-e vallásukat az emberek elé — akinek tetszik, belép, akinek nem, távol marad. Ésszerű lehetőséget kell adni arra, hogy a tömegek megértsék, mire hívják őket. Azt pedig, hogy a hithirdetők nyakát elvágják, és vastag falakat emeljenek eléjük, az iszlám erővel veri vissza."),
    E("ENG", "7f.1", "The Prophet (ﷺ) wanted to strengthen the ties between Islām and Christianity, though not at the expense of Islām. Thus he did not accept any bargaining over the issue of whether his missionaries should be left free to present their message to the mankind with the option of their accepting it or rejecting it. Islām strongly opposed the killing of its missionaries and the erection of barriers in the way of their work.",
      "The Prophet (ﷺ) resolved to set the relations between Islām and Christianity on firm foundations. He did not accept any bargaining over the issue of leaving his missionaries free to present their religion to the people — whoever liked it would enter it, and whoever disliked it would leave it. Reasonable opportunities must be given for the masses to understand what they are being invited to. But that the missionaries' necks should be cut and thick walls raised in their faces — this Islām resists by force."),
    # «ينكر سلطة رجالها… بين العباد وربهم» + dropped «فليس للإنسان إلا ما سعى… يخضع له عيسى وأمه»
    E("HUN", "7f.2", "amely tagadta személyiségeinek tekintélyét? Ez az új vallás azt vallotta, hogy nincsenek közvetítők az emberek és Isten között, és elvetette az engesztelés tanát, a kereszténység alapját, mert a jutalmat és büntetést egyedül az emberek tetteire alapozta.",
      "amely tagadta papsága tekintélyét? Ez az új vallás azt vallotta, hogy nincsenek közvetítők a szolgák és Uruk között, és elvetette az engesztelés tanát, a kereszténység alapját, mert a jutalmat és büntetést egyedül az emberek tetteire alapozta: az embernek csak az jár, amiért fáradozott, és egyetlen teherhordozó sem hordozza a másik terhét. Ezenfelül tagadta a társítást az istenségben: a világnak egyetlen Ura van, Akinek Jézus és anyja is alá van vetve."),
    E("ENG", "7f.2", "which denied the authority of its personages? This new religion held that there were no intermediaries between people and god, and it rejected the doctrine of the atonement, which was the basis of Christianity, because it considered reward and punishment to be based on people's actions alone.",
      "which denied the authority of its clergy? This new religion held that there were no intermediaries between the servants and their Lord, and it rejected the doctrine of the atonement, which was the basis of Christianity, because it considered reward and punishment to be based on people's actions alone: man has nothing but what he strives for, and no bearer of burdens shall bear another's burden. Moreover, it denied the principle of partnership in divinity: the world has only one Lord, to Whom Jesus and his mother are subject."),
    E("ENG", "7f.3", "The āyāt began by shipping up the zeal", "The āyāt began by whipping up the zeal"),
    # Q9:81 — AR quotes the whole verse
    E("HUN", "7f.4", "Akik otthon maradtak, örvendeztek, hogy Allah Küldöttének (ﷺ) háta mögött tétlenül ülhetnek, és idegenkedtek attól, hogy vagyonukkal és életükkel Allah útján küzdjenek. És azt mondták:\n\n(Ne vonuljatok ki a hőségben! Mondd: a pokol tüze hevesebb — ha értenék!) (Korán 9: 81)",
      "(Akik hátramaradtak, örvendeztek, hogy Allah Küldöttével szemben otthon ülhetnek, és idegenkedtek attól, hogy vagyonukkal és életükkel Allah útján küzdjenek, és azt mondták: Ne vonuljatok ki a hőségben! Mondd: a pokol tüze hevesebb hőségű — ha értenék!) (Korán 9: 81)"),
    E("ENG", "7f.4", "Those who remained at home rejoiced at sitting idle behind the back of the Messenger of Allāh (ﷺ), and were averse to striving with their wealth and their lives in Allāh's way. And they said:\n\n(Do not go out in the heat! Say: the heat of hell is more intense, if they but understood.) (Qur'ān 9: 81)",
      "(Those who were left behind rejoiced at sitting at home in opposition to the Messenger of Allāh, and were averse to striving with their wealth and their lives in Allāh's way, and they said: Do not go out in the heat! Say: the fire of hell is more intense in heat, if they but understood.) (Qur'ān 9: 81)"),
    # «فهيئا لى زادا» — provisions only
    E("HUN", "7f.5", "és megkérte őket, készítsenek neki vizet és útravalót.", "és megkérte őket, készítsenek neki útravalót."),
    E("ENG", "7f.5", "and he asked them to prepare water and provisions for him.", "and he asked them to prepare provisions for him."),
    # «لينفضوا أكراشها، ويشربوا ماءها»
    E("HUN", "7f.6", "és elkezdték levágni tevéiket, hogy púpjukból kinyerjék a vizet.", "és elkezdték levágni tevéiket, hogy kiürítsék a gyomrukat, és megigyák a benne lévő vizet."),
    E("ENG", "7f.6", "and they began to slaughter their camels to extract the water from their humps.", "and they began to slaughter their camels to empty out their stomachs and drink the water in them."),
    # «طلع البدر علينا» — two bayts as italic verse; ثنيات الوداع
    E("HUN", "7f.7", "„Felkelt felettünk a telihold Thanīyāt al Widā' felől.\n\nHálát kell adnunk, amíg csak dā'ī hív Allahhoz (ﷻ).\"",
      "*„Felkelt felettünk a telihold Thaniyyāt al-Wadā' felől;*\n\n*hálát kell adnunk, amíg csak dā'ī hív Allahhoz (ﷻ).\"*"),
    E("ENG", "7f.7", "\"The full moon has risen upon us from *Tanīyāt al Widā'*.\n\nWe must give thanks as long as a *Dā'ī* calls to Allāh (ﷻ).\"",
      "*\"The full moon has risen upon us from Thaniyyāt al-Wadā';*\n\n*we must give thanks as long as a dā'ī calls to Allāh (ﷻ).\"*"),
]
