# Front matter (Előszó, E könyv hadíszai, Hadísz-terminológia) — see opus55-findings.md "Front matter"
from apply import E

EDITS = [
    E("HUN", "F10", "minden személyiség legnagyobbikáról, Mohamedről (ﷺ)", "a legnagyobb Üzenet hordozójáról, Mohamedről (ﷺ)"),
    E("ENG", "F10", "about the greatest of all the personalities, Muhammad (ﷺ)", "about the bearer of the greatest Message, Muhammad (ﷺ)"),
    E("HUN", "F7", "ahogyan katonák írnának tábornokukról, alkalmazottak munkaadójukról vagy tanítványok", "ahogyan katonák írnának tábornokukról, követők urukról vagy tanítványok"),
    E("ENG", "F7", "as soldiers would write about their general or employees about their employer or pupils", "as soldiers would write about their general or a follower about his master or pupils"),
    E("HUN", "F2", "Nem lenne szabad újítaniuk. A formaságok kitalálásától való elfordulás nem kíván nagy erőfeszítést.", "Nincs is ezzel semmi gondjuk! Ezek a formák nem kívánnak tőlük olyan erőfeszítést, amelytől visszariadnának."),
    E("ENG", "F2", "They should not innovate. To turn away from inventing formalities does not require much efforts.", "And that is no burden for them! These forms cost them no effort from which they would shrink."),
    E("HUN", "F3", "evilági és lelki életében, abban, amit szeretett és amit nem, tudásában", "evilági és lelki életében, tudásában"),
    E("ENG", "F3", "in his worldly and spiritual life, in his likes and dislikes, in his knowledge", "in his worldly and spiritual life, in his knowledge"),
    E("HUN", "F1", "hasonló ahhoz, ami a zsidókat és a keresztényeket arra vitte, hogy mindenütt terjesszék", "éppen az, ami miatt a zsidók és a keresztények mindenütt terjesztik"),
    E("ENG", "F1", "is like the one what made the Jews and Christians broadcast it everywhere", "is what has made the Jews and Christians broadcast it everywhere"),
    E("HUN", "F8", "életének történetekké, *qaṣīdákká* és érthetetlen fohászokká", "életének történetekké, szerelmes *qaṣīdákká* (!) és érthetetlen fohászokká"),
    E("ENG", "F8", "life into stories, *qaṣīdahs* and unintelligible prayers", "life into stories, love *qaṣīdahs* (!) and unintelligible prayers"),
    E("HUN", "F9", "amely a tiszta irodalom, az egészséges elvek", "amely a tiszta erkölcs, az egészséges elvek"),
    E("ENG", "F9", "which gives the fragrance of pure literature, sound principles", "which gives the fragrance of pure manners, sound principles"),
    E("HUN", "F4", "De hogyan fejeződjék ki ez az érzés, és hogyan mutassa meg hűségét iránta? Ez az a kérdés, amely magyarázatra és tisztázásra szorul.", "Ám hogy egyedül ez az érzelem legyen az iránta való hűség megnyilvánulása — ez az, ami helyreigazításra és magyarázatra szorul."),
    E("ENG", "F4", "How should one make this feeling expressed and show its allegiance to him. This is the question that needs explanation and clarification.", "But that this emotion alone should be the expression of allegiance to him — that is what needs correcting and clarifying."),
    E("HUN", "F11a", "találkoztam egy csoport marokkóival", "találkoztam egy csoport maghrebivel (észak-afrikaival)"),
    E("ENG", "F11a", "meeting a group of Moroccans", "meeting a group of North Africans (from the Maghrib)"),
    E("HUN", "F11b", "amikor a franciák Marokkó három tartományát tartották megszállva", "amikor a franciák a három maghrebi országot tartották megszállva"),
    E("ENG", "F11b", "when the French had occupied three regions of Morocco", "when the French had occupied the three countries of the Maghrib"),
    E("HUN", "F5", "Mindez soha nem következett volna be, ha magát az Üzenetet világosan értenék, tanulmányoznák annak életét, aki elhozta, és szigorúan követnék tanítását.", "Ez pedig csak úgy érhető el, ha magát az Üzenetet mélyen megértik, igazán megismerik annak életét, aki elhozta, és szigorúan követik tanítását."),
    E("ENG", "F5", "This would never occur if the Message itself were clearly understood and the life of the one who conveyed it is studied and his teaching strictly followed.", "This can never be achieved except by a deep understanding of the Message itself, a true grasp of the life of the one who conveyed it and strict adherence to his teaching."),
    E("HUN", "F6", "És milyen drága, ha eszményi, biztos és megbízható!", "És milyen drága, ha tettre képes erő és hű elkötelezettség!"),
    E("ENG", "F6", "And how dear it is when it is ideal, safe and assured!", "And how precious it is when it is capability and loyal commitment!"),
    E("HUN", "F19", "Al-Tirmidhī és Al-Hākim általi", "Al-Tirmidhī és Al-Ḥākim általi"),
    E("ENG", "F19", "by Al-Tirmidhī and Al-Hākim", "by Al-Tirmidhī and Al-Ḥākim"),
    E("HUN", "F13", "Másfelől haboztam feljegyezni Muszlim és Bukhārī hadíszát", "Másfelől elzárkóztam attól, hogy feljegyezzem Muszlim és Bukhārī hadíszát"),
    E("ENG", "F13", "On the other hand, I hesitated to record the Ḥadīth", "On the other hand, I refrained from recording the Ḥadīth"),
    E("HUN", "F15", "Megelégedtem viszont a körülményekkel úgy, ahogyan Ibn Jarīr elbeszélte, aki — elbeszélésének Sejk Naṣiruddīn által feltárt gyengesége ellenére — összhangban áll", "Megnyugodtam viszont abban, ahogyan Ibn Jarīr beszélte el a körülményeket: elbeszélése — a Sejk Naṣiruddīn által feltárt gyengesége ellenére — összhangban áll"),
    E("HUN", "F17", "amikor gyenge és erős elbeszélésekkel egyaránt szembesül", "amikor gyenge és hiteles elbeszélésekkel egyaránt szembesül"),
    E("ENG", "F17", "when confronted by both weak and strong narrations", "when confronted by both weak and authentic narrations"),
    E("HUN", "F12", "Írtam Nāfi'nak — áldja meg Allah (ﷻ) —, és a harc előtti felszólításról kérdeztem. Azt válaszolta, hogy az az iszlám korai napjaiban volt, amikor a Próféta (ﷺ) váratlanul ütött rajta a Banū Muṣṭaliqon, megölte harcosaikat és foglyul ejtette asszonyaikat, és ekkor vette feleségül Juwairiyyát. Azt mondta, 'Abdullāh ibn 'Umar (رضي الله عنه) beszélte el neki, aki ott volt a seregben.",
      "Írtam Nāfi'nak — könyörüljön rajta Allah (ﷻ) —, és a harc előtti (iszlámra) hívásról kérdeztem. Azt írta vissza, hogy ez csak az iszlám korai időszakában volt így (!), hiszen a Próféta (ﷺ) váratlanul, gyanútlan állapotukban ütött rajta a Banū Muṣṭaliqon, megölte harcosaikat, foglyul ejtette asszonyaikat és gyermekeiket, és ekkor került hozzá Juwayriyah. Azt mondta, 'Abdullāh ibn 'Umar (رضي الله عنه) beszélte el neki — és ő ott volt abban a seregben!"),
    E("ENG", "F12", "I wrote to Nāfi', May Allāh (ﷻ) bless him, asking him about the supplication before fighting. He replied that, that was in the early days of Islām, when the Prophet (ﷺ) attacked the Banū Muṣṭaliq unawares and killed their fighters and took their women captive, and it was then that he took Juwairiyyah as wife. He said that 'Abdullāh ibn 'Umar (رضي الله عنه), who was in the army, told him about it.",
      "I wrote to Nāfi', may Allāh (ﷻ) have mercy on him, asking him about the call [to Islām] before fighting. He wrote back that this was only in the early days of Islām (!), for the Prophet (ﷺ) attacked the Banū Muṣṭaliq while they were unaware, killed their fighters and took their women and children captive, and it was on that day that he obtained Juwayriyah. He said that 'Abdullāh ibn 'Umar (رضي الله عنه) told him about it — and he was in that army!"),
    E("HUN", "F14", "az Ítélet Napjáig bekövetkező üldöztetésekről", "az Ítélet Napjáig bekövetkező megpróbáltatásokról (fitan)"),
    E("ENG", "F14", "informed them of the persecutions which would take place", "informed them of the trials (fitan) which would take place"),
    E("HUN", "F16", "megindokolni mindazt, amiben bizonyos dolgokban eltérek Sejk Naṣiruddīntól", "megindokolni mindazt, amiben eltérek Sejk Naṣiruddīntól"),
    E("HUN", "F18a", "*Mu'aḍḍal*: az *isnād*ból", "*Mu'ḍal*: az *isnād*ból"),
    E("ENG", "F18a", "*Mu'aḍḍal*: Two or more", "*Mu'ḍal*: Two or more"),
    E("HUN", "F18b", "*Mawḍū*: hazugok", "*Mawḍū'*: hazugok"),
    E("ENG", "F18b", "*Mawḍū*: A fabrication", "*Mawḍū'*: A fabrication"),
]
